# Banking Intent Assistant on BANKING77

PCAM ZG516 Applied Generative AI, Group Major Project, Assignment 1.

This notebook walks through the full workflow in order: dataset, model, baseline (E1), prompt comparison (E2),
decoding comparison (E3), structured output (E4), adaptation by retrieval against a classical reference (Req 8),
failure analysis (E6), the final tool-assisted assistant (E7), and its one-time evaluation on a held-out subset.

Every experiment lives in a `.py` file in the repository. The notebook imports those files; it does not copy the code.
Every experiment cell calls the model on the 100-row subset and recomputes the results.
Total time: about 25 minutes on an M3 Mac, about 8 minutes on a Colab T4 GPU.
To read the results in about one minute, skip the `%run` cells; the result cells load the saved `results_*.csv` files.

Full explanation of every step: `docs/PROGRESS.md`. Failure analysis: `docs/FAILURES.md`.

## 0. Setup

On Google Colab this clones the repository and installs the dependencies. Locally (after `uv sync`) it does nothing.

In [1]:
import os, sys
if "google.colab" in sys.modules:
    !git clone -q https://github.com/2025paml556-bhoomika/banking-agent.git
    %cd banking-agent
    %pip install -q transformers torch jsonschema pandas scikit-learn
if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")  # run from the project root so imports and evaluation/ paths work

# One variable selects the model for every cell below. Default: Qwen/Qwen2.5-1.5B-Instruct.
# To compare another Hugging Face chat model, set it here before any other cell runs.
# The model must have a chat template that accepts `tools` (main.py passes tool schemas to it).
# os.environ["MODEL"] = "Qwen/Qwen2.5-3B-Instruct"

import pandas as pd
pd.set_option("display.max_colwidth", 80)

## 1. Dataset (Req 2)

BANKING77: 13,083 online-banking customer messages, each labelled with one of 77 fine-grained intents.
Two fields: `text` and `category`. The dataset has a fixed train/test split.

We use the **train split** (10,003 rows) only as a source of labelled examples for few-shot prompts and retrieval.
Two fixed 100-row samples of the test split are used for evaluation:

- `eval_subset.csv` (seed 0): the development set. Every experiment below runs on it, and it chose the final system.
- `heldout_subset.csv` (seed 1, no overlap): the held-out set. Used once, by the final system only, in section 9.

The next cell rebuilds both files from `data/test.csv`. The seeds are fixed, so the rows are the same as the committed files.

In [ ]:
%run -m evaluation.make_eval_subset

In [2]:
train, test = pd.read_csv("data/train.csv"), pd.read_csv("data/test.csv")
subset = pd.read_csv("evaluation/eval_subset.csv")

print(f"train: {len(train)} rows, test: {len(test)} rows, intents: {train.category.nunique()}")
print(f"eval subset: {len(subset)} rows covering {subset.category.nunique()} intents")
print(f"message length (words): mean {train.text.str.split().str.len().mean():.1f}, max {train.text.str.split().str.len().max()}")
subset.head(8)

train: 10003 rows, test: 3080 rows, intents: 77
eval subset: 100 rows covering 53 intents
message length (words): mean 11.9, max 79

,text,category
0,How do I track my card?,card_arrival
1,How long should my new card take to arrive?,card_arrival
2,What foreign exchange rate will you use?,exchange_rate
3,when does the rate get determined,exchange_rate
4,Why am I unable to take money from my card but the statement says the transa...,pending_cash_withdrawal
5,I need my card quickly,card_delivery_estimate
6,When can I expect to receive my new card?,card_delivery_estimate
7,I can't get my card to work.,card_not_working

In [3]:
# Intent distribution in the train split (top and bottom 5) and one quirk: a single label with a capital letter.
counts = train.category.value_counts()
display(pd.concat([counts.head(5), counts.tail(5)]).to_frame("train rows"))
print("labels with a capital letter:", [c for c in counts.index if c != c.lower()])

                                                  train rows
category
card_payment_fee_charged                                 187
direct_debit_payment_not_recognised                      182
balance_not_updated_after_cheque_or_cash_deposit         181
wrong_amount_of_cash_received                            180
cash_withdrawal_charge                                   177
lost_or_stolen_card                                       82
card_swallowed                                            61
card_acceptance                                           59
virtual_card_not_working                                  41
contactless_not_working                                   35

labels with a capital letter: ['Refund_not_showing_up']

## 1b. Generative-model families (Req 3)

Req 3 asks us to **compare at least three generative-model families from CS1** and justify the choice of a causal LM.
Section 3 of the report does this as an analysis (autoregressive LM, VAE, GAN; diffusion discussed). Here we add
**measured evidence on our own data**. `src/generative_families.py` trains one small model of each family on the
10,003 BANKING77 train messages (NumPy only, CPU, about a minute):

| Family | What we trained | Native generation |
|---|---|---|
| Autoregressive | word-level trigram LM with backoff | one word at a time, each word fed back |
| VAE | bag-of-words encoder/decoder, 16-d latent | sample `z`, decode to word probabilities |
| GAN | bag-of-words generator + discriminator (straight-through for discrete words) | sample noise, run the generator |

These toy models are **not** the application model. Qwen2.5-1.5B-Instruct is the neural, large-scale member of the
autoregressive family. The point is to show on real banking text what each family can and cannot do for a
text-in / text-out assistant.

In [5]:
%run -m src.generative_families

10003 train messages, vocabulary 800 words, 91 banking keywords, mean length 12.0 words
                     family  empty_outputs_%  valid_bigrams_%  banking_word_%  distinct_outputs_%  mean_length  real_mean_length  follows_given_prefix_%  train_seconds                note
Autoregressive (trigram LM)              0.0            100.0            74.0                99.5         10.2              12.0                   100.0            0.1   likelihood: exact
         VAE (bag-of-words)              0.0             25.1            76.0               100.0         11.2              12.0                     0.0           13.1 ELBO loss/msg: 58.2
         GAN (bag-of-words)              0.0             32.8            78.5               100.0         12.3              12.0                     0.0           48.5       no likelihood

== Autoregressive (trigram LM)
  why is the status
  there is a payment i've made a debit card but it failed
  what is going to cancel my recent top up charges for using the app
  my pin
  how come
  can i still use my card pin
  why hasn't the transfer
  please explain why my top up if i don't know how much is the reason i am not recognizing a debit or credit card which

== VAE (bag-of-words)
  am me under an unable new send
  the there up do what it is the that i my
  or if didn't can prefer anywhere was reverted is card what fees with between they hour mugged is are am charged that purchased up multiple app currency foreign auto that know are automatic charges are
  deal up bank are like would what like often
  do everything there if as out countries of been the
  needs pin get but not card will was withdraw cancelled card refund was my compromised my pin virtual refund i
  but making not it cheque made the account a pending the ago
  why i why that there paying to is what order fee verify to

== GAN (bag-of-words)
  i my it a the to but account not status money this have reason pending hasn't through because up trying app returned since transaction atm think give appear
  i my but it and the a to as it's went ago sure payment rent already me have hello not something double them what made was couple tried hi been what's received enough days because two mind are taking wrong yesterday immediately problem pending checked requested making receiver make transferred transactions done someone keeps isn't were purchases during bank reverted freeze progress talk
  i to my the one app it have about if am us an out your amount aud no
  i my can us
  my is up a top there transfer
  i do us children
  i my to but card this you account can made received what from never see if arrived over by confirm may person
  i to my and a it can me need account one an if different seem into we cannot person were

== Autoregressive, continuing a prefix
  [i lost my] -> i lost my card
  [how do i] -> how do i order a new card has been a week since i didn't see any change in this country it is not working even
  [my card] -> my card keeps getting declined during top up limits
  [why was my] -> why was my exchange rate was applied to my savings account
  [can i top] -> can i top up not working because it hasn't gone through

total time 62s

**Reading the table** (200 generated messages per family):

- `valid_bigrams_%`: share of adjacent word pairs that occur in real customer messages. This metric favours the
  autoregressive model, because it is trained on exactly those pairs. It still shows the real point: VAE and GAN have **no
  model of word order**, so only about a quarter to a third of their word pairs are real.
- `follows_given_prefix_%`: can we steer the model with a text prefix (`how do i ...`)? This is what a prompt is.
  Only the autoregressive family supports it. VAE and GAN have no mechanism for it.
- `banking_word_%` and `distinct_outputs_%`: all three produce domain words and varied outputs, so these do not separate the families.
- A GAN has no likelihood to evaluate, and its words come out mostly frequent function words (`i my it a the to`).

**Conclusion for the project:** the assistant must read an arbitrary text instruction and continue it with an ordered,
valid label or reply. Only the autoregressive family does that, so a pretrained causal LM (Qwen) is the right choice.

In [6]:
g = pd.read_csv("evaluation/results/results_generative_families.csv")
g[["family", "valid_bigrams_%", "follows_given_prefix_%", "banking_word_%", "distinct_outputs_%", "train_seconds"]]

                        family  valid_bigrams_%  follows_given_prefix_%  banking_word_%  distinct_outputs_%  train_seconds
0  Autoregressive (trigram LM)            100.0                   100.0            74.0                99.5            0.1
1           VAE (bag-of-words)             25.1                     0.0            76.0               100.0           13.1
2           GAN (bag-of-words)             32.8                     0.0            78.5               100.0           48.5

## 2. Model (Req 4, Req 5)

`llm.py` loads a pretrained Hugging Face causal language model, `Qwen/Qwen2.5-1.5B-Instruct`, and exposes one
function, `generate(messages, max_new_tokens, tools, **decoding)`. Every experiment and the final assistant call
this function. Nothing else touches the model.

The cell below shows the four stages of autoregressive generation on a project example:
tokenization, embeddings, the language-modelling head (next-token logits), and the generation loop.

In [4]:
import torch
from src.llm import tokenizer, model, generate, DEVICE, MODEL

message = "How do I track my card?"
ids = tokenizer(message)["input_ids"]
print("1. tokenization:", [tokenizer.decode([i]) for i in ids], "->", ids)

emb = model.get_input_embeddings()(torch.tensor([ids]).to(DEVICE))
print("2. embeddings:  ", tuple(emb.shape), "(1 sequence, tokens, hidden size)")

with torch.no_grad():
    logits = model(torch.tensor([ids]).to(DEVICE)).logits[0, -1]
top = torch.topk(logits.float().softmax(-1), 5)
print("3. LM head, top-5 next tokens after the message:", [(tokenizer.decode([i]), round(p.item(), 3)) for p, i in zip(top.values, top.indices)])

print("4. autoregressive generation (greedy, chat format):")
print("  ", generate([{"role": "user", "content": message}], max_new_tokens=40))

/Users/anujkumar/wilp_AIML/banking_agent/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

21:38:32 llm: loading Qwen/Qwen2.5-1.5B-Instruct on mps

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 6956.44it/s]

21:38:47 llm: model ready, dtype torch.bfloat16, 1.5B parameters

1. tokenization: ['How', ' do', ' I', ' track', ' my', ' card', '?'] -> [4340, 653, 358, 3754, 847, 3701, 30]

2. embeddings:   (1, 7, 1536) (1 sequence, tokens, hidden size)

21:38:50 llm: LLM call: 36 prompt tokens, decoding={'do_sample': False}

3. LM head, top-5 next tokens after the message: [(' I', 0.097), (' To', 0.097), (' How', 0.075), (' You', 0.059), (' A', 0.031)]
4. autoregressive generation (greedy, chat format):

21:38:52 llm: LLM output (40 new tokens): "I'm sorry, but as an AI language model, I don't have access to your personal information or financial details. It's important to keep your sensitive data secure and not share it with anyone without"

   I'm sorry, but as an AI language model, I don't have access to your personal information or financial details. It's important to keep your sensitive data secure and not share it with anyone without

## 3. E1 Baseline (Req 5)

One simple prompt: the task, the 77 intent names, the message. No role, no examples, no output rules. Greedy decoding.
The output is free text, so `parse_intent` finds the longest intent name inside it.

**Result: accuracy 0.41.** For reference, a TF-IDF + logistic-regression classifier scores 0.79 on the same rows.

Run the experiment (about 2 minutes on an M3 Mac, less on a GPU):

In [5]:
%run -m src.baseline

21:38:52 baseline: loaded 77 intent names from the BANKING77 test split

21:38:52 baseline: E1 baseline: 100 test messages, greedy decoding, max 32 new tokens

21:38:52 baseline: --- row 1/100: 'How do I track my card?' (expected card_arrival)

21:38:52 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:38:53 llm: LLM output (19 new tokens): 'The intent for the message "How do I track my card?" is:\n\nCard_delivery_estimate'

21:38:53 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:38:53 baseline: --- row 2/100: 'How long should my new card take to arrive?' (expected card_arrival)

21:38:53 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:38:54 llm: LLM output (4 new tokens): 'Card_arrival'

21:38:54 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:38:54 baseline: --- row 3/100: 'What foreign exchange rate will you use?' (expected exchange_rate)

21:38:54 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:38:55 llm: LLM output (19 new tokens): 'The intent for the message "What foreign exchange rate will you use?" is:\n\nexchange_rate'

21:38:55 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:38:55 baseline: --- row 4/100: 'when does the rate get determined' (expected exchange_rate)

21:38:55 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:38:57 llm: LLM output (32 new tokens): 'The intent for the message "when does the rate get determined" is not explicitly listed in the provided categories. However, it seems to be related to currency conversion'

21:38:57 baseline: parse_intent: found nothing in output -> ''

21:38:57 baseline: --- row 5/100: 'Why am I unable to take money from my card but the statement says the transaction is still pending?' (expected pending_cash_withdrawal)

21:38:57 llm: LLM call: 437 prompt tokens, decoding={'do_sample': False}

21:38:58 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:38:58 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:38:58 baseline: --- row 6/100: 'I need my card quickly' (expected card_delivery_estimate)

21:38:58 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:38:59 llm: LLM output (4 new tokens): 'activate_my_card'

21:38:59 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:38:59 baseline: --- row 7/100: 'When can I expect to receive my new card?' (expected card_delivery_estimate)

21:38:59 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:00 llm: LLM output (26 new tokens): 'The intent for the message "When can I expect to receive my new card?" is **"card_arrival"**.'

21:39:00 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:39:00 baseline: --- row 8/100: "I can't get my card to work." (expected card_not_working)

21:39:00 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:39:01 llm: LLM output (4 new tokens): 'Card not working'

21:39:01 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:39:01 baseline: --- row 9/100: "My actual card isn't working." (expected card_not_working)

21:39:01 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:01 llm: LLM output (4 new tokens): 'Card_not_working'

21:39:01 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:39:01 baseline: --- row 10/100: 'What all currencies can be exchanged?' (expected exchange_via_app)

21:39:01 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:02 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:39:02 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:39:02 baseline: --- row 11/100: 'How do I exchange currency?' (expected exchange_via_app)

21:39:02 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:39:03 llm: LLM output (20 new tokens): 'The intent for the message "How do I exchange currency?" is:\n\nsupported_cards_and_currencies'

21:39:03 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:39:03 baseline: --- row 12/100: 'Can I open an account for a child?' (expected age_limit)

21:39:03 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:39:05 llm: LLM output (21 new tokens): 'The intent for the message "Can I open an account for a child?" is:\n\nget_physical_card'

21:39:05 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:39:05 baseline: --- row 13/100: 'How can I unblock a blocked pin number for my account?' (expected pin_blocked)

21:39:05 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:39:06 llm: LLM output (15 new tokens): 'The intent for the given message is "passcode_forgotten".'

21:39:06 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:39:06 baseline: --- row 14/100: 'Can you unblock my pin after too many wrong pin attempts?' (expected pin_blocked)

21:39:06 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:39:07 llm: LLM output (14 new tokens): 'The intent for this message is "passcode_forgotten".'

21:39:07 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:39:07 baseline: --- row 15/100: "Contactless isn't working for me" (expected contactless_not_working)

21:39:07 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:39:07 llm: LLM output (5 new tokens): 'Contactless_not_working'

21:39:07 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:39:07 baseline: --- row 16/100: 'My contactless is not working' (expected contactless_not_working)

21:39:07 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:09 llm: LLM output (20 new tokens): 'The intent for the message "My contactless is not working" is:\n\ncontactless_not_working'

21:39:09 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:39:09 baseline: --- row 17/100: 'Why is my top-up still outstanding?' (expected pending_top_up)

21:39:09 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:39:10 llm: LLM output (20 new tokens): 'The intent for the message "Why is my top-up still outstanding?" is:\n\ntop_up_failed'

21:39:10 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:39:10 baseline: --- row 18/100: 'I need to make an immediate cancellation related to a transfer. This was a mistake. Please assist quickly so this does not actually go through.' (expected cancel_transfer)

21:39:10 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:39:12 llm: LLM output (32 new tokens): 'The intent for the given message is:\n\n**cancel_transfer**\n\nThis message indicates that there has been a mistake with a transfer and the customer needs it canceled immediately.'

21:39:12 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:39:12 baseline: --- row 19/100: 'I tried to get $100 but I just got $20' (expected wrong_amount_of_cash_received)

21:39:12 llm: LLM call: 433 prompt tokens, decoding={'do_sample': False}

21:39:12 llm: LLM output (4 new tokens): 'top_up_failed'

21:39:12 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:39:12 baseline: --- row 20/100: "I tried to take out cash but the amount isn't right, so what do I do?" (expected wrong_amount_of_cash_received)

21:39:12 llm: LLM call: 436 prompt tokens, decoding={'do_sample': False}

21:39:14 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:39:14 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:39:14 baseline: --- row 21/100: 'I completed an in country transfer a few days ago and was sure to check the account information several times since the transaction was completed, but the funds are still not available. What is the problem?' (expected transfer_not_received_by_recipient)

21:39:14 llm: LLM call: 456 prompt tokens, decoding={'do_sample': False}

21:39:14 llm: LLM output (7 new tokens): 'Transfer_not_received_by_recipient'

21:39:14 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:39:14 baseline: --- row 22/100: 'My money transfer has not arrived.' (expected transfer_not_received_by_recipient)

21:39:14 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:16 llm: LLM output (18 new tokens): 'The intent for the message "My money transfer has not arrived" is:\n\npending_transfer'

21:39:16 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:39:16 baseline: --- row 23/100: 'help me obtain a virtual card' (expected getting_virtual_card)

21:39:16 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:16 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:39:16 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:39:16 baseline: --- row 24/100: 'Where is the virtual card located?' (expected getting_virtual_card)

21:39:16 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:18 llm: LLM output (19 new tokens): 'The intent for the message "Where is the virtual card located?" is:\n\nget_physical_card'

21:39:18 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:39:18 baseline: --- row 25/100: 'Can I order a virtual card?' (expected getting_virtual_card)

21:39:18 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:18 llm: LLM output (4 new tokens): 'get_physical_card'

21:39:18 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:39:18 baseline: --- row 26/100: 'Where are the virtual cards located?' (expected getting_virtual_card)

21:39:18 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:19 llm: LLM output (4 new tokens): 'get_physical_card'

21:39:19 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:39:19 baseline: --- row 27/100: 'Is my card usable anywhere?' (expected card_acceptance)

21:39:19 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:39:19 llm: LLM output (4 new tokens): 'activate_my_card'

21:39:19 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:39:19 baseline: --- row 28/100: 'Can I make online purchases with my card?' (expected card_acceptance)

21:39:19 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:39:20 llm: LLM output (4 new tokens): 'activate_my_card'

21:39:20 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:39:20 baseline: --- row 29/100: 'The application reverted my top-up.' (expected top_up_reverted)

21:39:20 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:21 llm: LLM output (20 new tokens): 'The intent for the message "The application reverted my top-up" is:\n\ntop_up_reverted'

21:39:21 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:39:21 baseline: --- row 30/100: 'On my last transaction it seem that my top-up was not successful.' (expected top_up_reverted)

21:39:21 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:39:22 llm: LLM output (4 new tokens): 'top_up_failed'

21:39:22 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:39:22 baseline: --- row 31/100: 'When I deposit cheques and cash, my balance does not update.' (expected balance_not_updated_after_cheque_or_cash_deposit)

21:39:22 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:39:23 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:39:23 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:39:23 baseline: --- row 32/100: "I tired to deposit some cash into my account but it's not there" (expected balance_not_updated_after_cheque_or_cash_deposit)

21:39:23 llm: LLM call: 432 prompt tokens, decoding={'do_sample': False}

21:39:24 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:39:24 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:39:24 baseline: --- row 33/100: 'I sent you a cheque couple days ago, nothing happened to my account yet! This is unacceptable, where is my money??' (expected balance_not_updated_after_cheque_or_cash_deposit)

21:39:24 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:39:25 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:39:25 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:39:25 baseline: --- row 34/100: 'What do i have to do to change my name?' (expected edit_personal_details)

21:39:25 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:39:26 llm: LLM output (25 new tokens): 'The intent for the message "What do I have to do to change my name?" is **edit_personal_details**.'

21:39:26 baseline: parse_intent: found ['edit_personal_details'] in output -> 'edit_personal_details'

21:39:26 baseline: --- row 35/100: 'Why do I have to give you all of my identification details?' (expected why_verify_identity)

21:39:26 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:39:27 llm: LLM output (4 new tokens): 'verify_my_identity'

21:39:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:39:27 baseline: --- row 36/100: 'Why is it asking me to verify my identity' (expected why_verify_identity)

21:39:27 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:28 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:39:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:39:28 baseline: --- row 37/100: 'Why did I need to verfiy my identity?' (expected why_verify_identity)

21:39:28 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:39:28 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:39:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:39:28 baseline: --- row 38/100: 'Can I give my friends access to my account so they can top it up for me?' (expected topping_up_by_card)

21:39:28 llm: LLM call: 435 prompt tokens, decoding={'do_sample': False}

21:39:29 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:39:29 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:39:29 baseline: --- row 39/100: 'How many card payments can I use on a disposable card?' (expected disposable_card_limits)

21:39:29 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:39:31 llm: LLM output (32 new tokens): 'The intent for the given message is "pending_transfer". This indicates that the user is inquiring about the number of card payments they can make with a disposable card'

21:39:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:39:31 baseline: --- row 40/100: 'Are you able to explain the restrictions of the disposable cards?' (expected disposable_card_limits)

21:39:31 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:39:32 llm: LLM output (14 new tokens): 'The intent for the given message is "disposable_card_limits".'

21:39:32 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:39:32 baseline: --- row 41/100: 'I have to have several disposable cards per day.' (expected disposable_card_limits)

21:39:32 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:33 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:39:33 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:39:33 baseline: --- row 42/100: 'What are the limits to using disposable virtual cards?' (expected disposable_card_limits)

21:39:33 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:34 llm: LLM output (13 new tokens): 'The intent for the given message is "Disposable Card Limits".'

21:39:34 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:39:34 baseline: --- row 43/100: 'My card was used without my permission.' (expected compromised_card)

21:39:34 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:39:35 llm: LLM output (21 new tokens): 'The intent for the message "My card was used without my permission" is:\n\nCompromised Card'

21:39:35 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:39:35 baseline: --- row 44/100: "I'm not certain, but someone may be using my card." (expected compromised_card)

21:39:35 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:39:36 llm: LLM output (13 new tokens): 'The intent for this message is "compromised_card".'

21:39:36 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:39:36 baseline: --- row 45/100: 'How many miles away is the ATM?' (expected atm_support)

21:39:36 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:39:38 llm: LLM output (32 new tokens): 'The given message "How many miles away is the ATM?" does not match any of the provided intents. It seems to be asking about the distance between an ATM'

21:39:38 baseline: parse_intent: found nothing in output -> ''

21:39:38 baseline: --- row 46/100: 'Where is the nearest bank machine?' (expected atm_support)

21:39:38 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:39 llm: LLM output (19 new tokens): 'The intent for the message "Where is the nearest bank machine?" is:\n\natm_support'

21:39:39 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:39:39 baseline: --- row 47/100: 'Can I use this card at an ATM?' (expected atm_support)

21:39:39 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:39:40 llm: LLM output (21 new tokens): 'The intent for the message "Can I use this card at an ATM?" is:\n\natm_support'

21:39:40 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:39:40 baseline: --- row 48/100: 'Why would I have a pending payment?' (expected pending_card_payment)

21:39:40 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:39:41 llm: LLM output (19 new tokens): 'The intent for the message "Why would I have a pending payment?" is:\n\npending_transfer'

21:39:41 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:39:41 baseline: --- row 49/100: "I've lost track of my phone or someone stole it." (expected lost_or_stolen_phone)

21:39:41 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:39:42 llm: LLM output (6 new tokens): 'Lost_or_stolen_phone'

21:39:42 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:39:42 baseline: --- row 50/100: 'Trouble transferring transaction contact for help' (expected declined_transfer)

21:39:42 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:39:43 llm: LLM output (6 new tokens): 'Transfer not received by recipient'

21:39:43 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:39:43 baseline: --- row 51/100: 'Still waiting on a refund.' (expected Refund_not_showing_up)

21:39:43 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:39:43 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:39:43 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:39:43 baseline: --- row 52/100: "Hi, As suggested by you, i have asked the seller to initiate the refund, it has been a week and i haven't received my money. Please advise." (expected Refund_not_showing_up)

21:39:43 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:39:44 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:39:44 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:39:44 baseline: --- row 53/100: 'How long will it take to get my refund' (expected Refund_not_showing_up)

21:39:44 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:46 llm: LLM output (25 new tokens): 'The intent for the message "How long will it take to get my refund" is Refund_not_showing_up.'

21:39:46 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:39:46 baseline: --- row 54/100: 'I have no idea why my card payment did not work.' (expected declined_card_payment)

21:39:46 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:39:47 llm: LLM output (16 new tokens): 'The intent for the given message is "card_payment_not_recognised".'

21:39:47 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:39:47 baseline: --- row 55/100: 'They declined my card payment.' (expected declined_card_payment)

21:39:47 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:39:48 llm: LLM output (19 new tokens): 'The intent for the message "They declined my card payment" is:\n\ndeclined_card_payment'

21:39:48 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:39:48 baseline: --- row 56/100: "This company isn't good, I would like to delete my account." (expected terminate_account)

21:39:48 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:39:49 llm: LLM output (11 new tokens): 'The intent for this message is "terminate_account".'

21:39:49 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:39:49 baseline: --- row 57/100: 'Can you tell me how to close my account?' (expected terminate_account)

21:39:49 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:49 llm: LLM output (3 new tokens): 'terminate_account'

21:39:49 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:39:49 baseline: --- row 58/100: 'I was at an ATM and it swallowed my card.' (expected card_swallowed)

21:39:49 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:39:51 llm: LLM output (32 new tokens): 'The intent for the message "I was at an ATM and it swallowed my card" is:\n\nCard_swallowed\n\nThis message indicates that the user encountered an issue'

21:39:51 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:39:51 baseline: --- row 59/100: 'What happens if my card is stuck in the ATM?' (expected card_swallowed)

21:39:51 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:39:53 llm: LLM output (32 new tokens): 'The intent for the message "What happens if my card is stuck in the ATM?" is:\n\nATM_support\n\nThis indicates that the user is seeking information about'

21:39:53 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:39:53 baseline: --- row 60/100: 'I made a payment that got charged twice instead of once.' (expected transaction_charged_twice)

21:39:53 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:39:54 llm: LLM output (14 new tokens): 'The intent for this message is "transaction_charged_twice".'

21:39:54 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:39:54 baseline: --- row 61/100: 'Can I verify the source of my funds?' (expected verify_source_of_funds)

21:39:54 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:39:55 llm: LLM output (6 new tokens): 'Verify_source_of_funds'

21:39:55 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:39:55 baseline: --- row 62/100: 'When does the money get transferred to my account' (expected transfer_timing)

21:39:55 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:39:55 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:39:55 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:39:55 baseline: --- row 63/100: 'How long do I have to wait for a transfer from the US?' (expected transfer_timing)

21:39:55 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:39:56 llm: LLM output (3 new tokens): 'Transfer_timing'

21:39:56 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:39:56 baseline: --- row 64/100: 'I am attempting to make a purchase online, but my card is not working.  I know there are funds available, is this an issue on the banks end?' (expected reverted_card_payment?)

21:39:56 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:39:58 llm: LLM output (32 new tokens): 'The intent for the given message is "card_not_working". The customer is reporting that their card is not functioning properly while they are trying to make a purchase online'

21:39:58 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:39:58 baseline: --- row 65/100: 'What do I need to do to change my PIN?' (expected change_pin)

21:39:58 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:39:59 llm: LLM output (32 new tokens): 'The intent for the message "What do I need to do to change my PIN?" is:\n\nchange_pin\n\nThis message clearly requests information on how to modify or'

21:39:59 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:39:59 baseline: --- row 66/100: 'What is the maximum I can transfer before I incur fees?' (expected transfer_fee_charged)

21:39:59 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:40:00 llm: LLM output (5 new tokens): 'Transfer_fee_charged'

21:40:00 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:40:00 baseline: --- row 67/100: 'What extra charges are there?' (expected transfer_fee_charged)

21:40:00 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:40:01 llm: LLM output (5 new tokens): 'Extra charge on statement'

21:40:01 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:40:01 baseline: --- row 68/100: 'Is it possible for me to get money out in a different currency?' (expected receiving_money)

21:40:01 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:40:01 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:40:01 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:40:01 baseline: --- row 69/100: 'What all is needed to verify the top-up card?' (expected verify_top_up)

21:40:01 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:40:03 llm: LLM output (26 new tokens): 'The intent for the given message "What all is needed to verify the top-up card?" is:\n\ntop_up_by_card_charge'

21:40:03 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:40:03 baseline: --- row 70/100: 'How is the top-up card verified?' (expected verify_top_up)

21:40:03 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:40:04 llm: LLM output (20 new tokens): 'The intent for the message "How is the top-up card verified?" is:\n\ntop_up_verification'

21:40:04 baseline: parse_intent: found nothing in output -> ''

21:40:04 baseline: --- row 71/100: 'The top-up verification code is missing' (expected verify_top_up)

21:40:04 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:40:05 llm: LLM output (20 new tokens): 'The intent for the message "The top-up verification code is missing" is:\n\nverify_my_identity'

21:40:05 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:40:05 baseline: --- row 72/100: 'Is there a fee for sending out more than one card?' (expected getting_spare_card)

21:40:05 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:40:07 llm: LLM output (31 new tokens): 'The intent for the given message is "top_up_by_card_charge". This indicates that the user is asking about fees associated with multiple card top-ups.'

21:40:07 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:40:07 baseline: --- row 73/100: 'Are there restrictions for ordering extra cards?' (expected getting_spare_card)

21:40:07 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:40:09 llm: LLM output (32 new tokens): 'The intent for the given message is "get_disposable_virtual_card". This indicates that the user is inquiring about restrictions or availability related to obtaining additional virtual cards'

21:40:09 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:40:09 baseline: --- row 74/100: "I'm looking for the cash deposit top up option but can't find it. Can you help me?" (expected top_up_by_cash_or_cheque)

21:40:09 llm: LLM call: 438 prompt tokens, decoding={'do_sample': False}

21:40:09 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:40:09 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:40:09 baseline: --- row 75/100: 'Where are the options to top up with a cheque on my account?' (expected top_up_by_cash_or_cheque)

21:40:09 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:40:10 llm: LLM output (6 new tokens): 'Top_up_by_card_charge'

21:40:10 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:40:10 baseline: --- row 76/100: 'How can I top up with this cheque I got?' (expected top_up_by_cash_or_cheque)

21:40:10 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:40:11 llm: LLM output (9 new tokens): 'Top_up_by_cheque_or_cash_deposit'

21:40:11 baseline: parse_intent: found nothing in output -> ''

21:40:11 baseline: --- row 77/100: 'Where can I get my card at?' (expected order_physical_card)

21:40:11 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:40:12 llm: LLM output (20 new tokens): 'The intent for the message "Where can I get my card at?" is:\n\nget_physical_card'

21:40:12 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:40:12 baseline: --- row 78/100: 'Where do I order my card?' (expected order_physical_card)

21:40:12 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:40:13 llm: LLM output (19 new tokens): 'The intent for the message "Where do I order my card?" is:\n\nget_physical_card'

21:40:13 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:40:13 baseline: --- row 79/100: 'My disposable virtual card is broken.' (expected virtual_card_not_working)

21:40:13 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:40:15 llm: LLM output (21 new tokens): 'The intent for the message "My disposable virtual card is broken." is:\n\nlost_or_stolen_card'

21:40:15 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:40:15 baseline: --- row 80/100: 'Why did the disposable virtual card which I used to pay a gym subscription get denied?' (expected virtual_card_not_working)

21:40:15 llm: LLM call: 434 prompt tokens, decoding={'do_sample': False}

21:40:17 llm: LLM output (32 new tokens): 'The intent for this message is "request_refund". The customer is asking about a refund because their disposable virtual card was denied when they tried to use it for'

21:40:17 baseline: parse_intent: found ['request_refund'] in output -> 'request_refund'

21:40:17 baseline: --- row 81/100: "Why isn't my virtual card working?" (expected virtual_card_not_working)

21:40:17 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:40:18 llm: LLM output (21 new tokens): 'The intent for the message "Why isn\'t my virtual card working?" is:\n\nvirtual_card_not_working'

21:40:18 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:40:18 baseline: --- row 82/100: 'Can I make a withdraw if I am out of country from with out any fees at an ATM?' (expected wrong_exchange_rate_for_cash_withdrawal)

21:40:18 llm: LLM call: 437 prompt tokens, decoding={'do_sample': False}

21:40:19 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:40:19 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:40:19 baseline: --- row 83/100: 'My cash withdrawal charged me the wrong exchange rate' (expected wrong_exchange_rate_for_cash_withdrawal)

21:40:19 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:40:20 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:40:20 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:40:20 baseline: --- row 84/100: 'Is there anyway, I can get a disposable virtual card?' (expected get_disposable_virtual_card)

21:40:20 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:40:21 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:40:21 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:40:21 baseline: --- row 85/100: "What's the deal? My card was just denied for top up. Why is it not going through?" (expected top_up_failed)

21:40:21 llm: LLM call: 438 prompt tokens, decoding={'do_sample': False}

21:40:22 llm: LLM output (32 new tokens): 'The intent for this message is "transfer_not_received_by_recipient". The customer is reporting that their card payment has been denied and is seeking an explanation as to'

21:40:22 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:40:22 baseline: --- row 86/100: "I don't think my top up is working correctly" (expected top_up_failed)

21:40:22 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:40:23 llm: LLM output (4 new tokens): 'top_up_failed'

21:40:23 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:40:23 baseline: --- row 87/100: "I just completed a bank transfer and the balance didn't update" (expected balance_not_updated_after_bank_transfer)

21:40:23 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:40:24 llm: LLM output (12 new tokens): 'The intent for this message is "top_up_failed".'

21:40:24 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:40:24 baseline: --- row 88/100: 'Why is my balance the same?  I processed a transfer.' (expected balance_not_updated_after_bank_transfer)

21:40:24 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:40:25 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:40:25 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:40:25 baseline: --- row 89/100: "I made a bank transfer a couple of hours ago from my UK account.  It hasn't appeared, can you check to make sure it went through?" (expected balance_not_updated_after_bank_transfer)

21:40:25 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:40:26 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:40:26 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:40:26 baseline: --- row 90/100: "There is a problem with my card. Somebody has removed money from my account in a town I haven't been to. Can you please freeze my account immediately?" (expected cash_withdrawal_not_recognised)

21:40:26 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:40:28 llm: LLM output (32 new tokens): 'The intent for this message is "declined_card_payment". The customer is reporting that someone has withdrawn money from their account without authorization and is requesting immediate action to'

21:40:28 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:40:28 baseline: --- row 91/100: 'Tell me how to go about activating my new card?' (expected activate_my_card)

21:40:28 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:40:28 llm: LLM output (4 new tokens): 'activate_my_card'

21:40:28 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:40:28 baseline: --- row 92/100: 'A fee was charged for my recent withdrawal.' (expected cash_withdrawal_charge)

21:40:28 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:40:29 llm: LLM output (14 new tokens): 'The intent for this message is "cash_withdrawal_charge".'

21:40:29 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:40:29 baseline: --- row 93/100: 'I got a fee for an ATM withdrawal.' (expected cash_withdrawal_charge)

21:40:29 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:40:31 llm: LLM output (23 new tokens): 'The intent for the message "I got a fee for an ATM withdrawal" is:\n\ncash_withdrawal_charge'

21:40:31 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:40:31 baseline: --- row 94/100: 'What do I do if my card is expiring soon?' (expected card_about_to_expire)

21:40:31 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:40:31 llm: LLM output (4 new tokens): 'Card_arrival'

21:40:31 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:40:31 baseline: --- row 95/100: "My top-up for Google Pay isn't working" (expected apple_pay_or_google_pay)

21:40:31 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:40:32 llm: LLM output (22 new tokens): 'The intent for the message "My top-up for Google Pay isn\'t working" is:\n\ntop_up_failed'

21:40:32 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:40:32 baseline: --- row 96/100: "Why isn't my top up working using my saved American Express in ApplePay?" (expected apple_pay_or_google_pay)

21:40:32 llm: LLM call: 433 prompt tokens, decoding={'do_sample': False}

21:40:33 llm: LLM output (12 new tokens): 'The intent for this message is "top_up_failed".'

21:40:33 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:40:33 baseline: --- row 97/100: 'What do you need for my identity check?' (expected verify_my_identity)

21:40:33 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:40:34 llm: LLM output (4 new tokens): 'verify_my_identity'

21:40:34 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:40:34 baseline: --- row 98/100: 'Are there any documents needed for the identity check?' (expected verify_my_identity)

21:40:34 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:40:35 llm: LLM output (4 new tokens): 'verify_my_identity'

21:40:35 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:40:35 baseline: --- row 99/100: 'Do I need any kind of documentation for the identity check?' (expected verify_my_identity)

21:40:35 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:40:35 llm: LLM output (4 new tokens): 'verify_my_identity'

21:40:35 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:40:35 baseline: --- row 100/100: "I need a card, but I'm in the US at the moment." (expected country_support)

21:40:35 llm: LLM call: 432 prompt tokens, decoding={'do_sample': False}

21:40:36 llm: LLM output (4 new tokens): 'activate_my_card'

21:40:36 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:40:36 baseline: saved results_baseline.csv with columns ['text', 'category', 'output', 'predicted', 'correct']

accuracy: 0.41
no intent found: 4

message:  How do I track my card?
output:   'The intent for the message "How do I track my card?" is:\n\nCard_delivery_estimate'
expected: card_arrival

message:  How long should my new card take to arrive?
output:   'Card_arrival'
expected: card_arrival

message:  What foreign exchange rate will you use?
output:   'The intent for the message "What foreign exchange rate will you use?" is:\n\nexchange_rate'
expected: exchange_rate

Results:

In [6]:
from src.baseline import build_prompt, parse_intent, INTENTS

print(build_prompt("How do I track my card?")[0]["content"][:200], "...\n")
r = pd.read_csv("evaluation/results/results_baseline.csv")
print(f"accuracy {r.correct.mean():.2f}, no valid intent {r.predicted.isna().sum()}, outputs with preamble {r.output.str.match(r'^\s*The').sum()}")
r[["text", "category", "output", "predicted", "correct"]].head(5)

21:40:37 baseline: loaded 77 intent names from the BANKING77 test split

Classify the customer message into one of these intents:
Refund_not_showing_up, activate_my_card, age_limit, apple_pay_or_google_pay, atm_support, automatic_top_up, balance_not_updated_after_bank_tran ...

accuracy 0.41, no valid intent 4, outputs with preamble 57

,text,category,output,predicted,correct
0,How do I track my card?,card_arrival,"The intent for the message ""How do I track my card?"" is:\n\nCard_delivery_es...",card_delivery_estimate,False
1,How long should my new card take to arrive?,card_arrival,Card_arrival,card_arrival,True
2,What foreign exchange rate will you use?,exchange_rate,"The intent for the message ""What foreign exchange rate will you use?"" is:\n\...",exchange_rate,True
3,when does the rate get determined,exchange_rate,"The intent for the message ""when does the rate get determined"" is not explic...",NaN,False
4,Why am I unable to take money from my card but the statement says the transa...,pending_cash_withdrawal,"The intent for this message is ""pending_transfer"".",pending_transfer,False

## 4. E2 Prompt comparison (Req 6, Req 11)

`prompts.build_prompt(message, style)` is the reusable, parameterised template. Five styles, each adding one thing to the baseline:
role line, constraint line ("exact intent name, nothing else, always choose one"), 5 random solved examples, and examples + constraint.

**Result:** accuracy barely moves (0.40 to 0.43). Format changes a lot: the constraint removed all preamble text and halved the invented names.
Instructions cannot supply knowledge the model lacks, namely where the boundary between near-synonym labels lies.

Run the experiment (about 8 minutes on an M3 Mac, less on a GPU):

In [7]:
%run -m src.prompts

21:40:45 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:40:47 llm: LLM output (19 new tokens): 'The intent for the message "How do I track my card?" is:\n\nCard_delivery_estimate'

21:40:47 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:40:47 llm: LLM output (4 new tokens): 'Card_arrival'

21:40:47 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:40:49 llm: LLM output (19 new tokens): 'The intent for the message "What foreign exchange rate will you use?" is:\n\nexchange_rate'

21:40:49 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:40:50 llm: LLM output (32 new tokens): 'The intent for the message "when does the rate get determined" is not explicitly listed in the provided categories. However, it seems to be related to currency conversion'

21:40:50 llm: LLM call: 437 prompt tokens, decoding={'do_sample': False}

21:40:51 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:40:51 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:40:52 llm: LLM output (4 new tokens): 'activate_my_card'

21:40:52 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:40:53 llm: LLM output (26 new tokens): 'The intent for the message "When can I expect to receive my new card?" is **"card_arrival"**.'

21:40:53 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:40:54 llm: LLM output (4 new tokens): 'Card not working'

21:40:54 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:40:54 llm: LLM output (4 new tokens): 'Card_not_working'

21:40:54 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:40:55 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:40:55 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:40:56 llm: LLM output (20 new tokens): 'The intent for the message "How do I exchange currency?" is:\n\nsupported_cards_and_currencies'

21:40:56 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:40:58 llm: LLM output (21 new tokens): 'The intent for the message "Can I open an account for a child?" is:\n\nget_physical_card'

21:40:58 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:40:59 llm: LLM output (15 new tokens): 'The intent for the given message is "passcode_forgotten".'

21:40:59 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:41:00 llm: LLM output (14 new tokens): 'The intent for this message is "passcode_forgotten".'

21:41:00 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:00 llm: LLM output (5 new tokens): 'Contactless_not_working'

21:41:00 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:01 llm: LLM output (20 new tokens): 'The intent for the message "My contactless is not working" is:\n\ncontactless_not_working'

21:41:02 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:03 llm: LLM output (20 new tokens): 'The intent for the message "Why is my top-up still outstanding?" is:\n\ntop_up_failed'

21:41:03 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:41:04 llm: LLM output (32 new tokens): 'The intent for the given message is:\n\n**cancel_transfer**\n\nThis message indicates that there has been a mistake with a transfer and the customer needs it canceled immediately.'

21:41:04 llm: LLM call: 433 prompt tokens, decoding={'do_sample': False}

21:41:05 llm: LLM output (4 new tokens): 'top_up_failed'

21:41:05 llm: LLM call: 436 prompt tokens, decoding={'do_sample': False}

21:41:06 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:41:06 llm: LLM call: 456 prompt tokens, decoding={'do_sample': False}

21:41:07 llm: LLM output (7 new tokens): 'Transfer_not_received_by_recipient'

21:41:07 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:08 llm: LLM output (18 new tokens): 'The intent for the message "My money transfer has not arrived" is:\n\npending_transfer'

21:41:08 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:09 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:41:09 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:10 llm: LLM output (19 new tokens): 'The intent for the message "Where is the virtual card located?" is:\n\nget_physical_card'

21:41:10 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:11 llm: LLM output (4 new tokens): 'get_physical_card'

21:41:11 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:11 llm: LLM output (4 new tokens): 'get_physical_card'

21:41:11 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:41:12 llm: LLM output (4 new tokens): 'activate_my_card'

21:41:12 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:41:12 llm: LLM output (4 new tokens): 'activate_my_card'

21:41:12 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:14 llm: LLM output (20 new tokens): 'The intent for the message "The application reverted my top-up" is:\n\ntop_up_reverted'

21:41:14 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:41:14 llm: LLM output (4 new tokens): 'top_up_failed'

21:41:14 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:41:15 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:41:15 llm: LLM call: 432 prompt tokens, decoding={'do_sample': False}

21:41:16 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:41:16 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:41:17 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:41:17 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:41:19 llm: LLM output (25 new tokens): 'The intent for the message "What do I have to do to change my name?" is **edit_personal_details**.'

21:41:19 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:41:19 llm: LLM output (4 new tokens): 'verify_my_identity'

21:41:19 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:41:20 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:41:20 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:41:20 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:41:20 llm: LLM call: 435 prompt tokens, decoding={'do_sample': False}

21:41:21 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:41:21 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:23 llm: LLM output (32 new tokens): 'The intent for the given message is "pending_transfer". This indicates that the user is inquiring about the number of card payments they can make with a disposable card'

21:41:23 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:24 llm: LLM output (14 new tokens): 'The intent for the given message is "disposable_card_limits".'

21:41:24 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:41:24 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:41:24 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:41:25 llm: LLM output (13 new tokens): 'The intent for the given message is "Disposable Card Limits".'

21:41:25 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:27 llm: LLM output (21 new tokens): 'The intent for the message "My card was used without my permission" is:\n\nCompromised Card'

21:41:27 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:41:28 llm: LLM output (13 new tokens): 'The intent for this message is "compromised_card".'

21:41:28 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:29 llm: LLM output (32 new tokens): 'The given message "How many miles away is the ATM?" does not match any of the provided intents. It seems to be asking about the distance between an ATM'

21:41:29 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:31 llm: LLM output (19 new tokens): 'The intent for the message "Where is the nearest bank machine?" is:\n\natm_support'

21:41:31 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:41:32 llm: LLM output (21 new tokens): 'The intent for the message "Can I use this card at an ATM?" is:\n\natm_support'

21:41:32 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:33 llm: LLM output (19 new tokens): 'The intent for the message "Why would I have a pending payment?" is:\n\npending_transfer'

21:41:33 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:34 llm: LLM output (6 new tokens): 'Lost_or_stolen_phone'

21:41:34 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:41:34 llm: LLM output (6 new tokens): 'Transfer not received by recipient'

21:41:34 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:41:35 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:41:35 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:41:36 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:41:36 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:41:37 llm: LLM output (25 new tokens): 'The intent for the message "How long will it take to get my refund" is Refund_not_showing_up.'

21:41:37 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:38 llm: LLM output (16 new tokens): 'The intent for the given message is "card_payment_not_recognised".'

21:41:38 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:41:40 llm: LLM output (19 new tokens): 'The intent for the message "They declined my card payment" is:\n\ndeclined_card_payment'

21:41:40 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:41:40 llm: LLM output (11 new tokens): 'The intent for this message is "terminate_account".'

21:41:40 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:41:41 llm: LLM output (3 new tokens): 'terminate_account'

21:41:41 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:41:43 llm: LLM output (32 new tokens): 'The intent for the message "I was at an ATM and it swallowed my card" is:\n\nCard_swallowed\n\nThis message indicates that the user encountered an issue'

21:41:43 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:41:44 llm: LLM output (32 new tokens): 'The intent for the message "What happens if my card is stuck in the ATM?" is:\n\nATM_support\n\nThis indicates that the user is seeking information about'

21:41:44 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:45 llm: LLM output (14 new tokens): 'The intent for this message is "transaction_charged_twice".'

21:41:45 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:41:46 llm: LLM output (6 new tokens): 'Verify_source_of_funds'

21:41:46 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:41:47 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:41:47 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:41:48 llm: LLM output (3 new tokens): 'Transfer_timing'

21:41:48 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:41:49 llm: LLM output (32 new tokens): 'The intent for the given message is "card_not_working". The customer is reporting that their card is not functioning properly while they are trying to make a purchase online'

21:41:49 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:41:51 llm: LLM output (32 new tokens): 'The intent for the message "What do I need to do to change my PIN?" is:\n\nchange_pin\n\nThis message clearly requests information on how to modify or'

21:41:51 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:52 llm: LLM output (5 new tokens): 'Transfer_fee_charged'

21:41:52 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:41:52 llm: LLM output (5 new tokens): 'Extra charge on statement'

21:41:52 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:41:53 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:41:53 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:41:55 llm: LLM output (26 new tokens): 'The intent for the given message "What all is needed to verify the top-up card?" is:\n\ntop_up_by_card_charge'

21:41:55 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:56 llm: LLM output (20 new tokens): 'The intent for the message "How is the top-up card verified?" is:\n\ntop_up_verification'

21:41:56 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:41:57 llm: LLM output (20 new tokens): 'The intent for the message "The top-up verification code is missing" is:\n\nverify_my_identity'

21:41:57 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:41:59 llm: LLM output (31 new tokens): 'The intent for the given message is "top_up_by_card_charge". This indicates that the user is asking about fees associated with multiple card top-ups.'

21:41:59 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:42:00 llm: LLM output (32 new tokens): 'The intent for the given message is "get_disposable_virtual_card". This indicates that the user is inquiring about restrictions or availability related to obtaining additional virtual cards'

21:42:00 llm: LLM call: 438 prompt tokens, decoding={'do_sample': False}

21:42:01 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:42:01 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:42:02 llm: LLM output (6 new tokens): 'Top_up_by_card_charge'

21:42:02 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:42:03 llm: LLM output (9 new tokens): 'Top_up_by_cheque_or_cash_deposit'

21:42:03 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:42:04 llm: LLM output (20 new tokens): 'The intent for the message "Where can I get my card at?" is:\n\nget_physical_card'

21:42:04 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:42:05 llm: LLM output (19 new tokens): 'The intent for the message "Where do I order my card?" is:\n\nget_physical_card'

21:42:05 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:42:07 llm: LLM output (21 new tokens): 'The intent for the message "My disposable virtual card is broken." is:\n\nlost_or_stolen_card'

21:42:07 llm: LLM call: 434 prompt tokens, decoding={'do_sample': False}

21:42:08 llm: LLM output (32 new tokens): 'The intent for this message is "request_refund". The customer is asking about a refund because their disposable virtual card was denied when they tried to use it for'

21:42:08 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:42:09 llm: LLM output (21 new tokens): 'The intent for the message "Why isn\'t my virtual card working?" is:\n\nvirtual_card_not_working'

21:42:09 llm: LLM call: 437 prompt tokens, decoding={'do_sample': False}

21:42:11 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:42:11 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:42:12 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:42:12 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:42:12 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:42:12 llm: LLM call: 438 prompt tokens, decoding={'do_sample': False}

21:42:14 llm: LLM output (32 new tokens): 'The intent for this message is "transfer_not_received_by_recipient". The customer is reporting that their card payment has been denied and is seeking an explanation as to'

21:42:14 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:42:15 llm: LLM output (4 new tokens): 'top_up_failed'

21:42:15 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:42:16 llm: LLM output (12 new tokens): 'The intent for this message is "top_up_failed".'

21:42:16 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:42:16 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:42:16 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:42:17 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:42:17 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:42:19 llm: LLM output (32 new tokens): 'The intent for this message is "declined_card_payment". The customer is reporting that someone has withdrawn money from their account without authorization and is requesting immediate action to'

21:42:19 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:42:20 llm: LLM output (4 new tokens): 'activate_my_card'

21:42:20 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:42:21 llm: LLM output (14 new tokens): 'The intent for this message is "cash_withdrawal_charge".'

21:42:21 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:42:22 llm: LLM output (23 new tokens): 'The intent for the message "I got a fee for an ATM withdrawal" is:\n\ncash_withdrawal_charge'

21:42:22 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:42:23 llm: LLM output (4 new tokens): 'Card_arrival'

21:42:23 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:42:24 llm: LLM output (22 new tokens): 'The intent for the message "My top-up for Google Pay isn\'t working" is:\n\ntop_up_failed'

21:42:24 llm: LLM call: 433 prompt tokens, decoding={'do_sample': False}

21:42:25 llm: LLM output (12 new tokens): 'The intent for this message is "top_up_failed".'

21:42:25 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:42:25 llm: LLM output (4 new tokens): 'verify_my_identity'

21:42:25 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:42:26 llm: LLM output (4 new tokens): 'verify_my_identity'

21:42:26 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:42:27 llm: LLM output (4 new tokens): 'verify_my_identity'

21:42:27 llm: LLM call: 432 prompt tokens, decoding={'do_sample': False}

21:42:27 llm: LLM output (4 new tokens): 'activate_my_card'

21:42:27 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:42:27 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:42:27 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:42:27 baseline: parse_intent: found nothing in output -> ''

21:42:27 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:42:27 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:42:27 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:42:27 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:42:27 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:42:27 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:42:27 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:42:27 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:42:27 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:42:27 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:42:27 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:42:27 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:42:27 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:42:27 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:42:27 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:42:27 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:42:27 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:42:27 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:42:27 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:42:27 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:42:27 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:42:27 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:42:27 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:42:27 baseline: parse_intent: found ['edit_personal_details'] in output -> 'edit_personal_details'

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:42:27 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:42:27 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:42:27 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:42:27 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:42:27 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:42:27 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:42:27 baseline: parse_intent: found nothing in output -> ''

21:42:27 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:42:27 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:42:27 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:42:27 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:42:27 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:42:27 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:42:27 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:42:27 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:42:27 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:42:27 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:42:27 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:42:27 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:42:27 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:42:27 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:42:27 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:42:27 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:42:27 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:42:27 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:42:27 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:42:27 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:42:27 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:42:27 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:42:27 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:42:27 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:42:27 baseline: parse_intent: found nothing in output -> ''

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:42:27 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:42:27 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:42:27 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:42:27 baseline: parse_intent: found nothing in output -> ''

21:42:27 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:42:27 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:42:27 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:42:27 baseline: parse_intent: found ['request_refund'] in output -> 'request_refund'

21:42:27 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:42:27 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:42:27 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:42:27 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:42:27 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:42:27 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:42:27 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:42:27 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:42:27 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:42:27 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:42:27 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:42:27 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:42:27 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

== zero_shot: accuracy 0.41
  'How do I track my card?' -> 'The intent for the message "How do I track my card?" is:\n\nCard_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'Card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'The intent for the message "What foreign exchange rate will you use?" is:\n\nexchange_rate' (expected exchange_rate)

21:42:29 llm: LLM output (32 new tokens): 'The intent for this message is "get_physical_card". The customer is asking about tracking their physical card, which falls under the category of requesting information on how to'

21:42:29 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:42:30 llm: LLM output (4 new tokens): 'Card_arrival'

21:42:30 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:42:30 llm: LLM output (3 new tokens): 'Exchange_rate'

21:42:30 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:31 llm: LLM output (11 new tokens): 'The intent for this message is "exchange_rate".'

21:42:31 llm: LLM call: 432 prompt tokens, decoding={'do_sample': False}

21:42:32 llm: LLM output (14 new tokens): 'The intent for this message is "pending_cash_withdrawal".'

21:42:32 llm: LLM call: 418 prompt tokens, decoding={'do_sample': False}

21:42:33 llm: LLM output (4 new tokens): 'activate_my_card'

21:42:33 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:42:33 llm: LLM output (4 new tokens): 'Card_arrival'

21:42:33 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:42:34 llm: LLM output (4 new tokens): 'Card_not_working'

21:42:34 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:35 llm: LLM output (4 new tokens): 'Card_not_working'

21:42:35 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:35 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:42:35 llm: LLM call: 418 prompt tokens, decoding={'do_sample': False}

21:42:36 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:42:36 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:42:38 llm: LLM output (32 new tokens): 'The intent for this message is "get_disposable_virtual_card". The customer is asking about opening an account for a child, which falls under the category of obtaining'

21:42:38 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:42:39 llm: LLM output (30 new tokens): 'The intent for this message is "passcode_forgotten". The customer is seeking assistance to unblock their blocked PIN number on the account.'

21:42:39 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:42:40 llm: LLM output (3 new tokens): 'Change_pin'

21:42:40 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:42:40 llm: LLM output (5 new tokens): 'Contactless_not_working'

21:42:40 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:41 llm: LLM output (5 new tokens): 'Contactless_not_working'

21:42:41 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:42:42 llm: LLM output (4 new tokens): 'Top_up_failed'

21:42:42 llm: LLM call: 440 prompt tokens, decoding={'do_sample': False}

21:42:43 llm: LLM output (7 new tokens): 'Transfer_not_received_by_recipient'

21:42:43 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:42:43 llm: LLM output (4 new tokens): 'top_up_failed'

21:42:43 llm: LLM call: 431 prompt tokens, decoding={'do_sample': False}

21:42:44 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:42:44 llm: LLM call: 451 prompt tokens, decoding={'do_sample': False}

21:42:45 llm: LLM output (7 new tokens): 'Transfer_not_received_by_recipient'

21:42:45 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:46 llm: LLM output (7 new tokens): 'Transfer_not_received_by_recipient'

21:42:46 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:47 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:42:47 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:47 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:42:47 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:48 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:42:48 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:49 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:42:49 llm: LLM call: 418 prompt tokens, decoding={'do_sample': False}

21:42:49 llm: LLM output (4 new tokens): 'activate_my_card'

21:42:49 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:42:50 llm: LLM output (4 new tokens): 'activate_my_card'

21:42:50 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:42:51 llm: LLM output (20 new tokens): 'The intent of the message "The application reverted my top-up" is:\n\ntop_up_reverted'

21:42:51 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:42:52 llm: LLM output (4 new tokens): 'top_up_failed'

21:42:52 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:42:53 llm: LLM output (10 new tokens): 'Balance_not_updated_after_cheque_or_cash_deposit'

21:42:53 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:42:53 llm: LLM output (7 new tokens): 'Intent: cheque_or_cash_deposit'

21:42:53 llm: LLM call: 438 prompt tokens, decoding={'do_sample': False}

21:42:54 llm: LLM output (10 new tokens): 'Balance_not_updated_after_cheque_or_cash_deposit'

21:42:54 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:42:55 llm: LLM output (12 new tokens): 'The intent for this message is "edit_personal_details".'

21:42:55 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:42:56 llm: LLM output (4 new tokens): 'verify_my_identity'

21:42:56 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:42:56 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:42:56 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:42:57 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:42:57 llm: LLM call: 430 prompt tokens, decoding={'do_sample': False}

21:42:58 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:42:58 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:42:59 llm: LLM output (32 new tokens): 'The intent of this message is "pending_transfer". The customer is asking about the limitations or restrictions related to using their card for transfers, which falls under the category'

21:42:59 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:00 llm: LLM output (13 new tokens): 'The intent of this message is "disposable_card_limits".'

21:43:00 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:01 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:43:01 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:02 llm: LLM output (12 new tokens): 'The intent for this message is "Disposable Card Limits".'

21:43:02 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:03 llm: LLM output (13 new tokens): 'The intent for this message is "compromised_card".'

21:43:03 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:43:03 llm: LLM output (4 new tokens): 'Card_not_working'

21:43:03 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:05 llm: LLM output (32 new tokens): 'The given message "How many miles away is the ATM?" does not match any of the provided intents related to banking services or transactions. It appears to be asking'

21:43:05 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:43:07 llm: LLM output (32 new tokens): 'The given message "Where is the nearest bank machine?" falls under the intent of **atm_support**. This query is typically related to finding the location of'

21:43:07 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:43:07 llm: LLM output (4 new tokens): 'ATM_support'

21:43:07 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:08 llm: LLM output (6 new tokens): 'Intent: pending_card_payment'

21:43:08 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:09 llm: LLM output (6 new tokens): 'Lost_or_stolen_phone'

21:43:09 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:43:10 llm: LLM output (6 new tokens): 'Transfer not received by recipient'

21:43:10 llm: LLM call: 418 prompt tokens, decoding={'do_sample': False}

21:43:10 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:43:10 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:43:11 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:43:11 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:12 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:43:12 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:13 llm: LLM output (15 new tokens): 'The intent for this message is "transfer_not_received_by_recipient".'

21:43:13 llm: LLM call: 418 prompt tokens, decoding={'do_sample': False}

21:43:14 llm: LLM output (19 new tokens): 'The intent of the message "They declined my card payment" is:\n\ndeclined_card_payment'

21:43:14 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:43:15 llm: LLM output (3 new tokens): 'terminate_account'

21:43:15 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:15 llm: LLM output (3 new tokens): 'terminate_account'

21:43:15 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:16 llm: LLM output (4 new tokens): 'Card_swallowed'

21:43:16 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:17 llm: LLM output (12 new tokens): 'The intent for this message is "atm_support".'

21:43:17 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:17 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:43:17 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:43:18 llm: LLM output (4 new tokens): 'Verify_my_identity'

21:43:18 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:19 llm: LLM output (11 new tokens): 'The intent for this message is "pending_transfer".'

21:43:19 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:43:19 llm: LLM output (3 new tokens): 'Transfer_timing'

21:43:19 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:43:20 llm: LLM output (4 new tokens): 'Card_not_working'

21:43:20 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:21 llm: LLM output (23 new tokens): 'The intent of the customer message "What do I need to do to change my PIN?" is:\n\nChange_pin'

21:43:21 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:22 llm: LLM output (5 new tokens): 'Transfer_fee_charged'

21:43:22 llm: LLM call: 418 prompt tokens, decoding={'do_sample': False}

21:43:23 llm: LLM output (5 new tokens): 'Extra charge on statement'

21:43:23 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:43:23 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:43:23 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:24 llm: LLM output (14 new tokens): 'The intent for this message is "top_up_by_card_charge".'

21:43:24 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:26 llm: LLM output (22 new tokens): 'The intent of the message "How is the top-up card verified?" is:\n\ntop_up_by_card_charge'

21:43:26 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:27 llm: LLM output (12 new tokens): 'The intent for this message is "top_up_failed".'

21:43:27 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:28 llm: LLM output (32 new tokens): 'The intent for this message is "supported_cards_and_currencies". The customer is asking about fees associated with sending multiple cards, which falls under the category of supported'

21:43:28 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:29 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:43:29 llm: LLM call: 433 prompt tokens, decoding={'do_sample': False}

21:43:30 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:43:30 llm: LLM call: 426 prompt tokens, decoding={'do_sample': False}

21:43:30 llm: LLM output (6 new tokens): 'Top_up_by_card_charge'

21:43:30 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:31 llm: LLM output (6 new tokens): 'Top_up_by_cheque'

21:43:31 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:32 llm: LLM output (4 new tokens): 'Card_arrival'

21:43:32 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:43:33 llm: LLM output (12 new tokens): 'The intent for this message is "get_physical_card".'

21:43:33 llm: LLM call: 419 prompt tokens, decoding={'do_sample': False}

21:43:33 llm: LLM output (4 new tokens): 'Card_not_working'

21:43:33 llm: LLM call: 429 prompt tokens, decoding={'do_sample': False}

21:43:34 llm: LLM output (14 new tokens): 'The intent for this message is "get_disposable_virtual_card".'

21:43:34 llm: LLM call: 420 prompt tokens, decoding={'do_sample': False}

21:43:35 llm: LLM output (13 new tokens): 'The intent for this message is "virtual_card_not_working".'

21:43:35 llm: LLM call: 432 prompt tokens, decoding={'do_sample': False}

21:43:36 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:43:36 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:38 llm: LLM output (17 new tokens): 'The intent for this message is "cash_withdrawal_not_recognised".'

21:43:38 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:38 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:43:38 llm: LLM call: 433 prompt tokens, decoding={'do_sample': False}

21:43:40 llm: LLM output (32 new tokens): 'The intent for this message is "transfer_not_received_by_recipient". The customer is experiencing issues with their card being denied during a top-up process and wants to'

21:43:40 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:41 llm: LLM output (4 new tokens): 'top_up_failed'

21:43:41 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:43:41 llm: LLM output (12 new tokens): 'Intent: Transfer_not_updated_After_Bank_Transfer'

21:43:41 llm: LLM call: 425 prompt tokens, decoding={'do_sample': False}

21:43:42 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:43:42 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:43:43 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:43:43 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:43:45 llm: LLM output (32 new tokens): 'The intent for this message is "lost_or_stolen_card". The customer is reporting that someone has accessed their account without authorization and has withdrawn funds, indicating they'

21:43:45 llm: LLM call: 423 prompt tokens, decoding={'do_sample': False}

21:43:45 llm: LLM output (4 new tokens): 'activate_my_card'

21:43:45 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:43:46 llm: LLM output (6 new tokens): 'Transaction_charged_twice'

21:43:46 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:43:47 llm: LLM output (6 new tokens): 'Transaction_charged_twice'

21:43:47 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:47 llm: LLM output (4 new tokens): 'Card_arrival'

21:43:47 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:48 llm: LLM output (6 new tokens): 'Top_up_by_card_charge'

21:43:48 llm: LLM call: 428 prompt tokens, decoding={'do_sample': False}

21:43:49 llm: LLM output (6 new tokens): 'Top_up_by_card_charge'

21:43:49 llm: LLM call: 421 prompt tokens, decoding={'do_sample': False}

21:43:49 llm: LLM output (4 new tokens): 'verify_my_identity'

21:43:49 llm: LLM call: 422 prompt tokens, decoding={'do_sample': False}

21:43:50 llm: LLM output (4 new tokens): 'verify_my_identity'

21:43:50 llm: LLM call: 424 prompt tokens, decoding={'do_sample': False}

21:43:51 llm: LLM output (4 new tokens): 'verify_my_identity'

21:43:51 llm: LLM call: 427 prompt tokens, decoding={'do_sample': False}

21:43:51 llm: LLM output (4 new tokens): 'get_physical_card'

21:43:51 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:43:51 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:43:51 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:43:51 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:43:51 baseline: parse_intent: found ['pending_cash_withdrawal'] in output -> 'pending_cash_withdrawal'

21:43:51 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:43:51 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:43:51 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:43:51 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:43:51 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:43:51 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:43:51 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:43:51 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:43:51 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:43:51 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:43:51 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:43:51 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:43:51 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:43:51 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:43:51 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:43:51 baseline: parse_intent: found nothing in output -> ''

21:43:51 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:43:51 baseline: parse_intent: found ['edit_personal_details'] in output -> 'edit_personal_details'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:43:51 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:43:51 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:43:51 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:43:51 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:43:51 baseline: parse_intent: found nothing in output -> ''

21:43:51 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:43:51 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:43:51 baseline: parse_intent: found ['pending_card_payment'] in output -> 'pending_card_payment'

21:43:51 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:43:51 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:43:51 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:43:51 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:43:51 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:43:51 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:43:51 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:43:51 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:43:51 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:43:51 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:43:51 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:43:51 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:43:51 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:43:51 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:43:51 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:43:51 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:43:51 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:43:51 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:43:51 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:43:51 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:43:51 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:43:51 baseline: parse_intent: found nothing in output -> ''

21:43:51 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:43:51 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:43:51 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:43:51 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:43:51 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:43:51 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:43:51 baseline: parse_intent: found nothing in output -> ''

21:43:51 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:43:51 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:43:51 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:43:51 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:43:51 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:43:51 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:43:51 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:43:51 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:43:51 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:43:51 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:43:51 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

== role: accuracy 0.40
  'How do I track my card?' -> 'The intent for this message is "get_physical_card". The customer is asking about tracking their physical card, which falls under the category of requesting information on how to' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'Card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'Exchange_rate' (expected exchange_rate)

21:43:52 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:43:52 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:43:52 llm: LLM output (4 new tokens): 'card_arrival'

21:43:52 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:43:53 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:43:53 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:43:54 llm: LLM output (3 new tokens): 'exchange_rate'

21:43:54 llm: LLM call: 456 prompt tokens, decoding={'do_sample': False}

21:43:54 llm: LLM output (3 new tokens): 'pending_transfer'

21:43:54 llm: LLM call: 442 prompt tokens, decoding={'do_sample': False}

21:43:55 llm: LLM output (4 new tokens): 'card_arrival'

21:43:55 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:43:56 llm: LLM output (4 new tokens): 'card_arrival'

21:43:56 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:43:56 llm: LLM output (4 new tokens): 'card_not_working'

21:43:56 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:43:57 llm: LLM output (4 new tokens): 'card_not_working'

21:43:57 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:43:58 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:43:58 llm: LLM call: 442 prompt tokens, decoding={'do_sample': False}

21:43:59 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:43:59 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:44:01 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:01 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:44:02 llm: LLM output (6 new tokens): 'passcode_forgotten'

21:44:02 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:44:03 llm: LLM output (6 new tokens): 'passcode_forgotten'

21:44:03 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:04 llm: LLM output (5 new tokens): 'contactless_not_working'

21:44:04 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:05 llm: LLM output (5 new tokens): 'contactless_not_working'

21:44:05 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:05 llm: LLM output (4 new tokens): 'top_up_failed'

21:44:05 llm: LLM call: 464 prompt tokens, decoding={'do_sample': False}

21:44:06 llm: LLM output (3 new tokens): 'cancel_transfer'

21:44:06 llm: LLM call: 452 prompt tokens, decoding={'do_sample': False}

21:44:07 llm: LLM output (4 new tokens): 'top_up_failed'

21:44:07 llm: LLM call: 455 prompt tokens, decoding={'do_sample': False}

21:44:07 llm: LLM output (6 new tokens): 'wrong_amount_of_cash_received'

21:44:07 llm: LLM call: 475 prompt tokens, decoding={'do_sample': False}

21:44:09 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:44:09 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:09 llm: LLM output (3 new tokens): 'pending_transfer'

21:44:09 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:10 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:10 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:11 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:11 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:11 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:11 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:12 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:12 llm: LLM call: 442 prompt tokens, decoding={'do_sample': False}

21:44:12 llm: LLM output (4 new tokens): 'card_acceptance'

21:44:12 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:44:13 llm: LLM output (4 new tokens): 'activate_my_card'

21:44:13 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:14 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:44:14 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:44:14 llm: LLM output (4 new tokens): 'top_up_failed'

21:44:14 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:44:15 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:44:15 llm: LLM call: 451 prompt tokens, decoding={'do_sample': False}

21:44:16 llm: LLM output (9 new tokens): 'cash_withdrawal_not_recognised'

21:44:16 llm: LLM call: 462 prompt tokens, decoding={'do_sample': False}

21:44:17 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:44:17 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:18 llm: LLM output (4 new tokens): 'edit_personal_details'

21:44:18 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:44:18 llm: LLM output (4 new tokens): 'verify_my_identity'

21:44:18 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:19 llm: LLM output (4 new tokens): 'verify_my_identity'

21:44:19 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:20 llm: LLM output (4 new tokens): 'verify_my_identity'

21:44:20 llm: LLM call: 454 prompt tokens, decoding={'do_sample': False}

21:44:20 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:44:20 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:21 llm: LLM output (3 new tokens): 'pending_transfer'

21:44:21 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:22 llm: LLM output (5 new tokens): 'disposable_card_limits'

21:44:22 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:22 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:44:22 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:23 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:44:23 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:24 llm: LLM output (5 new tokens): 'compromised_card'

21:44:24 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:44:24 llm: LLM output (5 new tokens): 'compromised_card'

21:44:24 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:25 llm: LLM output (4 new tokens): 'atm_support'

21:44:25 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:26 llm: LLM output (4 new tokens): 'atm_support'

21:44:26 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:44:26 llm: LLM output (4 new tokens): 'atm_support'

21:44:26 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:27 llm: LLM output (4 new tokens): 'pending_card_payment'

21:44:27 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:28 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:44:28 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:28 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:44:28 llm: LLM call: 442 prompt tokens, decoding={'do_sample': False}

21:44:29 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:44:29 llm: LLM call: 469 prompt tokens, decoding={'do_sample': False}

21:44:30 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:44:30 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:31 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:44:31 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:31 llm: LLM output (7 new tokens): 'card_payment_not_recognised'

21:44:31 llm: LLM call: 442 prompt tokens, decoding={'do_sample': False}

21:44:32 llm: LLM output (5 new tokens): 'declined_card_payment'

21:44:32 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:44:33 llm: LLM output (3 new tokens): 'terminate_account'

21:44:33 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:33 llm: LLM output (3 new tokens): 'terminate_account'

21:44:33 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:34 llm: LLM output (4 new tokens): 'card_swallowed'

21:44:34 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:34 llm: LLM output (4 new tokens): 'card_arrival'

21:44:34 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:35 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:44:35 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:44:36 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:44:36 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:36 llm: LLM output (3 new tokens): 'pending_transfer'

21:44:36 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:44:37 llm: LLM output (3 new tokens): 'pending_transfer'

21:44:37 llm: LLM call: 469 prompt tokens, decoding={'do_sample': False}

21:44:38 llm: LLM output (4 new tokens): 'card_not_working'

21:44:38 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:38 llm: LLM output (3 new tokens): 'change_pin'

21:44:38 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:39 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:44:39 llm: LLM call: 442 prompt tokens, decoding={'do_sample': False}

21:44:40 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:44:40 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:44:40 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:44:40 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:41 llm: LLM output (4 new tokens): 'verify_my_identity'

21:44:41 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:42 llm: LLM output (4 new tokens): 'verify_my_identity'

21:44:42 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:42 llm: LLM output (4 new tokens): 'verify_my_identity'

21:44:42 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:43 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:44:43 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:44 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:44:44 llm: LLM call: 457 prompt tokens, decoding={'do_sample': False}

21:44:45 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:44:45 llm: LLM call: 450 prompt tokens, decoding={'do_sample': False}

21:44:45 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:44:45 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:46 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:44:46 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:47 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:47 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:48 llm: LLM output (4 new tokens): 'get_physical_card'

21:44:48 llm: LLM call: 443 prompt tokens, decoding={'do_sample': False}

21:44:48 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:44:48 llm: LLM call: 453 prompt tokens, decoding={'do_sample': False}

21:44:49 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:44:49 llm: LLM call: 444 prompt tokens, decoding={'do_sample': False}

21:44:50 llm: LLM output (4 new tokens): 'card_not_working'

21:44:50 llm: LLM call: 456 prompt tokens, decoding={'do_sample': False}

21:44:50 llm: LLM output (9 new tokens): 'cash_withdrawal_not_recognised'

21:44:50 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:51 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:44:51 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:52 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:44:52 llm: LLM call: 457 prompt tokens, decoding={'do_sample': False}

21:44:53 llm: LLM output (4 new tokens): 'declined_transfer'

21:44:53 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:53 llm: LLM output (4 new tokens): 'top_up_failed'

21:44:53 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:44:54 llm: LLM output (4 new tokens): 'top_up_failed'

21:44:54 llm: LLM call: 449 prompt tokens, decoding={'do_sample': False}

21:44:55 llm: LLM output (3 new tokens): 'pending_transfer'

21:44:55 llm: LLM call: 467 prompt tokens, decoding={'do_sample': False}

21:44:55 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:44:55 llm: LLM call: 468 prompt tokens, decoding={'do_sample': False}

21:44:56 llm: LLM output (5 new tokens): 'compromised_card'

21:44:56 llm: LLM call: 447 prompt tokens, decoding={'do_sample': False}

21:44:57 llm: LLM output (4 new tokens): 'activate_my_card'

21:44:57 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:44:57 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:44:57 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:44:58 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:44:58 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:44:59 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:44:59 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:44:59 llm: LLM output (4 new tokens): 'top_up_failed'

21:44:59 llm: LLM call: 452 prompt tokens, decoding={'do_sample': False}

21:45:00 llm: LLM output (4 new tokens): 'top_up_failed'

21:45:00 llm: LLM call: 445 prompt tokens, decoding={'do_sample': False}

21:45:01 llm: LLM output (4 new tokens): 'verify_my_identity'

21:45:01 llm: LLM call: 446 prompt tokens, decoding={'do_sample': False}

21:45:01 llm: LLM output (4 new tokens): 'verify_my_identity'

21:45:01 llm: LLM call: 448 prompt tokens, decoding={'do_sample': False}

21:45:02 llm: LLM output (4 new tokens): 'verify_my_identity'

21:45:02 llm: LLM call: 451 prompt tokens, decoding={'do_sample': False}

21:45:03 llm: LLM output (4 new tokens): 'get_physical_card'

21:45:03 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:45:03 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:45:03 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:45:03 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:45:03 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:45:03 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:45:03 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:45:03 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:45:03 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:45:03 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:45:03 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:45:03 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:45:03 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:45:03 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['wrong_amount_of_cash_received'] in output -> 'wrong_amount_of_cash_received'

21:45:03 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:45:03 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:45:03 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:45:03 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:45:03 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:45:03 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:45:03 baseline: parse_intent: found ['edit_personal_details'] in output -> 'edit_personal_details'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:45:03 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:45:03 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:45:03 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:45:03 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:45:03 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:45:03 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:45:03 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:45:03 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:45:03 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:45:03 baseline: parse_intent: found ['pending_card_payment'] in output -> 'pending_card_payment'

21:45:03 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:45:03 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:45:03 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:45:03 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:45:03 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:45:03 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:45:03 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:45:03 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:45:03 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:45:03 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:45:03 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:45:03 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:45:03 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:45:03 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:45:03 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:45:03 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:45:03 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:45:03 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:45:03 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:45:03 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:45:03 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:45:03 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:45:03 baseline: parse_intent: found nothing in output -> ''

21:45:03 baseline: parse_intent: found nothing in output -> ''

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:45:03 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:45:03 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:45:03 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:45:03 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:45:03 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:45:03 baseline: parse_intent: found ['declined_transfer'] in output -> 'declined_transfer'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:45:03 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:45:03 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:45:03 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:45:03 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:45:03 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:45:03 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:45:03 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:45:03 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

== constraint: accuracy 0.40
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'supported_cards_and_currencies' (expected exchange_rate)

21:45:04 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:45:04 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:04 llm: LLM output (3 new tokens): 'Card arrival'

21:45:04 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:45:05 llm: LLM output (3 new tokens): 'exchange_rate'

21:45:05 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:07 llm: LLM output (32 new tokens): 'The given message "When does the rate get determined?" falls under the intent category of **exchange_rate**. This indicates that the user is seeking information about the'

21:45:07 llm: LLM call: 576 prompt tokens, decoding={'do_sample': False}

21:45:08 llm: LLM output (3 new tokens): 'pending_transfer'

21:45:08 llm: LLM call: 562 prompt tokens, decoding={'do_sample': False}

21:45:08 llm: LLM output (6 new tokens): 'Intent: card_arrival'

21:45:08 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:09 llm: LLM output (4 new tokens): 'card_arrival'

21:45:09 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:45:10 llm: LLM output (4 new tokens): 'card_not_working'

21:45:10 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:11 llm: LLM output (4 new tokens): 'card_not_working'

21:45:11 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:12 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:45:12 llm: LLM call: 562 prompt tokens, decoding={'do_sample': False}

21:45:12 llm: LLM output (5 new tokens): 'Intent: exchange_currency'

21:45:12 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:45:14 llm: LLM output (32 new tokens): 'None of the provided messages match any of the given intents exactly. However, they could potentially relate to some of the following intents:\n\n- **pending_transfer**\n-'

21:45:14 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:45:15 llm: LLM output (3 new tokens): 'pin_blocked'

21:45:15 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:45:16 llm: LLM output (3 new tokens): 'pin_blocked'

21:45:16 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:45:17 llm: LLM output (5 new tokens): 'contactless_not_working'

21:45:17 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:17 llm: LLM output (7 new tokens): 'Intent: contactless_not_working'

21:45:17 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:45:18 llm: LLM output (7 new tokens): 'Intent: top_up_reverted'

21:45:18 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:45:19 llm: LLM output (3 new tokens): 'cancel_transfer'

21:45:19 llm: LLM call: 572 prompt tokens, decoding={'do_sample': False}

21:45:20 llm: LLM output (4 new tokens): 'top_up_failed'

21:45:20 llm: LLM call: 575 prompt tokens, decoding={'do_sample': False}

21:45:21 llm: LLM output (11 new tokens): 'Intent: cash_withdrawal_not_recognised'

21:45:21 llm: LLM call: 595 prompt tokens, decoding={'do_sample': False}

21:45:22 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:45:22 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:23 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:45:23 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:24 llm: LLM output (4 new tokens): 'get_virtual_card'

21:45:24 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:24 llm: LLM output (6 new tokens): 'intent: get_virtual_card'

21:45:24 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:25 llm: LLM output (4 new tokens): 'get_virtual_card'

21:45:25 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:26 llm: LLM output (6 new tokens): 'intent: get_virtual_card'

21:45:26 llm: LLM call: 562 prompt tokens, decoding={'do_sample': False}

21:45:27 llm: LLM output (4 new tokens): 'card_acceptance'

21:45:27 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:45:28 llm: LLM output (4 new tokens): 'activate_my_card'

21:45:28 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:28 llm: LLM output (7 new tokens): 'Intent: revert_card_payment?'

21:45:28 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:45:29 llm: LLM output (4 new tokens): 'top_up_failed'

21:45:29 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:45:30 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:45:30 llm: LLM call: 571 prompt tokens, decoding={'do_sample': False}

21:45:31 llm: LLM output (6 new tokens): 'Intent: top_up_failed'

21:45:31 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:45:32 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:45:32 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:45:34 llm: LLM output (32 new tokens): 'None of the provided intents match the given message "What do i have to do to change my name?". The message appears to be asking about changing personal details'

21:45:34 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:45:35 llm: LLM output (4 new tokens): 'verify_my_identity'

21:45:35 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:35 llm: LLM output (4 new tokens): 'verify_my_identity'

21:45:35 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:45:36 llm: LLM output (4 new tokens): 'verify_my_identity'

21:45:36 llm: LLM call: 574 prompt tokens, decoding={'do_sample': False}

21:45:37 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:45:37 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:45:38 llm: LLM output (3 new tokens): 'pending_transfer'

21:45:38 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:45:39 llm: LLM output (6 new tokens): 'intent: disposable_card_limits'

21:45:39 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:39 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:45:39 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:40 llm: LLM output (3 new tokens): 'pending_transfer'

21:45:40 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:45:41 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:45:41 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:45:42 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:45:42 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:45:43 llm: LLM output (32 new tokens): 'None of the provided messages match any of the given intents exactly. However, they could potentially relate to some of the following intents:\n\n- **pending_transfer**\n-'

21:45:44 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:45 llm: LLM output (32 new tokens): 'None of the provided intents match the given message "Where is the nearest bank machine?" The message appears to be asking about the location of an ATM or bank machine'

21:45:45 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:45:46 llm: LLM output (4 new tokens): 'card_acceptance'

21:45:46 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:45:47 llm: LLM output (5 new tokens): 'Intent: pending_transfer'

21:45:47 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:45:48 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:45:48 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:45:49 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:45:49 llm: LLM call: 562 prompt tokens, decoding={'do_sample': False}

21:45:50 llm: LLM output (9 new tokens): 'Intent: Refund_not_showing_up'

21:45:50 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:45:50 llm: LLM output (6 new tokens): 'Intent: request_refund'

21:45:50 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:51 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:45:51 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:45:52 llm: LLM output (9 new tokens): 'Intent: card_payment_not_recognised'

21:45:52 llm: LLM call: 562 prompt tokens, decoding={'do_sample': False}

21:45:53 llm: LLM output (6 new tokens): 'Intent: declined_card_payment'

21:45:53 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:45:54 llm: LLM output (3 new tokens): 'terminate_account'

21:45:54 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:55 llm: LLM output (3 new tokens): 'terminate_account'

21:45:55 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:45:55 llm: LLM output (6 new tokens): 'intent: card_swallowed'

21:45:55 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:45:56 llm: LLM output (4 new tokens): 'card_not_working'

21:45:56 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:45:57 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:45:57 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:45:58 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:45:58 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:45:59 llm: LLM output (5 new tokens): 'Intent: transfer_timing'

21:45:59 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:45:59 llm: LLM output (3 new tokens): 'transfer_timing'

21:45:59 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:46:00 llm: LLM output (6 new tokens): 'intent: card_not_working'

21:46:00 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:46:01 llm: LLM output (3 new tokens): 'change_pin'

21:46:01 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:46:02 llm: LLM output (4 new tokens): 'top_up_limits'

21:46:02 llm: LLM call: 562 prompt tokens, decoding={'do_sample': False}

21:46:03 llm: LLM output (5 new tokens): 'Intent: exchange_charge'

21:46:03 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:46:03 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:46:03 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:46:04 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:46:04 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:46:05 llm: LLM output (6 new tokens): 'Intent: verify_top_up'

21:46:05 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:46:06 llm: LLM output (8 new tokens): 'Intent: verify_source_of_funds'

21:46:06 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:46:07 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:46:07 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:46:08 llm: LLM output (8 new tokens): 'intent: get_disposable_virtual_card'

21:46:08 llm: LLM call: 577 prompt tokens, decoding={'do_sample': False}

21:46:09 llm: LLM output (10 new tokens): 'Intent: top_up_by_cash_or_cheque'

21:46:09 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:46:10 llm: LLM output (8 new tokens): 'Intent: top_up_by_cheque'

21:46:10 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:46:11 llm: LLM output (11 new tokens): 'Intent: top_up_by_cheque_or_cash_deposit'

21:46:11 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:46:12 llm: LLM output (6 new tokens): 'intent: get_physical_card'

21:46:12 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:46:12 llm: LLM output (6 new tokens): 'Intent: get_physical_card'

21:46:12 llm: LLM call: 563 prompt tokens, decoding={'do_sample': False}

21:46:13 llm: LLM output (7 new tokens): 'intent: virtual_card_not_working'

21:46:13 llm: LLM call: 573 prompt tokens, decoding={'do_sample': False}

21:46:14 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:46:14 llm: LLM call: 564 prompt tokens, decoding={'do_sample': False}

21:46:15 llm: LLM output (7 new tokens): 'intent: virtual_card_not_working'

21:46:15 llm: LLM call: 576 prompt tokens, decoding={'do_sample': False}

21:46:16 llm: LLM output (7 new tokens): 'Intent: unable_to_verify_identity'

21:46:16 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:46:17 llm: LLM output (11 new tokens): 'Intent: wrong_exchange_rate_for_cash_withdrawal'

21:46:17 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:46:18 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:46:18 llm: LLM call: 577 prompt tokens, decoding={'do_sample': False}

21:46:19 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:46:19 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:46:19 llm: LLM output (6 new tokens): 'Intent: top_up_failed'

21:46:20 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:46:20 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:46:20 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:46:21 llm: LLM output (6 new tokens): 'refund_not_shown_up'

21:46:21 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:46:22 llm: LLM output (6 new tokens): 'refund_not_shown_up'

21:46:22 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:46:23 llm: LLM output (8 new tokens): 'intent: lost_or_stolen_card'

21:46:23 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:46:24 llm: LLM output (4 new tokens): 'activate_my_card'

21:46:24 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:46:25 llm: LLM output (7 new tokens): 'Intent: transfer_fee_charged'

21:46:25 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:46:26 llm: LLM output (8 new tokens): 'Intent: cash_withdrawal_charge'

21:46:26 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:46:27 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:46:27 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:46:27 llm: LLM output (6 new tokens): 'Intent: top_up_failed'

21:46:27 llm: LLM call: 572 prompt tokens, decoding={'do_sample': False}

21:46:28 llm: LLM output (8 new tokens): 'intent: top_up_by_card_charge'

21:46:28 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:46:29 llm: LLM output (4 new tokens): 'verify_my_identity'

21:46:29 llm: LLM call: 566 prompt tokens, decoding={'do_sample': False}

21:46:30 llm: LLM output (4 new tokens): 'verify_my_identity'

21:46:30 llm: LLM call: 568 prompt tokens, decoding={'do_sample': False}

21:46:31 llm: LLM output (4 new tokens): 'verify_my_identity'

21:46:31 llm: LLM call: 571 prompt tokens, decoding={'do_sample': False}

21:46:31 llm: LLM output (4 new tokens): 'get_physical_card'

21:46:31 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:46:31 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:46:31 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:46:31 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:46:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:46:31 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:46:31 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:46:31 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:46:31 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:46:31 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:46:31 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:46:31 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:46:31 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:46:31 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:46:31 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:46:31 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:46:31 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:46:31 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:46:31 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:46:31 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:46:31 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:46:31 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:46:31 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:46:31 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:46:31 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:46:31 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:46:31 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:46:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:46:31 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:46:31 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:46:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:46:31 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:46:31 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:46:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:46:31 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:46:31 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:46:31 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:46:31 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:46:31 baseline: parse_intent: found ['request_refund'] in output -> 'request_refund'

21:46:31 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:46:31 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:46:31 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:46:31 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:46:31 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:46:31 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:46:31 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:46:31 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:46:31 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:46:31 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:46:31 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:46:31 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:46:31 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:46:31 baseline: parse_intent: found ['top_up_limits'] in output -> 'top_up_limits'

21:46:31 baseline: parse_intent: found ['exchange_charge'] in output -> 'exchange_charge'

21:46:31 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:46:31 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:46:31 baseline: parse_intent: found ['verify_top_up'] in output -> 'verify_top_up'

21:46:31 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:46:31 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:46:31 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:46:31 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:46:31 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:46:31 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:46:31 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:46:31 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:46:31 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:46:31 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:46:31 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:46:31 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:46:31 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:46:31 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found nothing in output -> ''

21:46:31 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:46:31 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:46:31 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:46:31 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:46:31 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:46:31 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:46:31 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:46:31 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:46:31 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:46:31 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:46:31 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:46:31 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

== few_shot: accuracy 0.43
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'Card arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

21:46:32 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:46:32 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:46:33 llm: LLM output (4 new tokens): 'card_arrival'

21:46:33 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:46:34 llm: LLM output (3 new tokens): 'exchange_rate'

21:46:34 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:35 llm: LLM output (3 new tokens): 'exchange_rate'

21:46:35 llm: LLM call: 595 prompt tokens, decoding={'do_sample': False}

21:46:35 llm: LLM output (3 new tokens): 'pending_transfer'

21:46:35 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:46:36 llm: LLM output (4 new tokens): 'card_arrival'

21:46:36 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:46:37 llm: LLM output (4 new tokens): 'card_arrival'

21:46:37 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:46:38 llm: LLM output (4 new tokens): 'card_not_working'

21:46:38 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:39 llm: LLM output (4 new tokens): 'card_not_working'

21:46:39 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:39 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:46:39 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:46:40 llm: LLM output (3 new tokens): 'exchange_currency'

21:46:40 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:46:42 llm: LLM output (32 new tokens): 'None of the provided intents match the given message "Can I open an account for a child?". The message does not fit any of the categories listed in the'

21:46:42 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:46:43 llm: LLM output (6 new tokens): 'passcode_forgotten'

21:46:43 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:46:44 llm: LLM output (3 new tokens): 'pin_blocked'

21:46:44 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:46:45 llm: LLM output (5 new tokens): 'contactless_not_working'

21:46:45 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:45 llm: LLM output (5 new tokens): 'contactless_not_working'

21:46:45 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:46:46 llm: LLM output (5 new tokens): 'top_up_reverted'

21:46:46 llm: LLM call: 603 prompt tokens, decoding={'do_sample': False}

21:46:47 llm: LLM output (3 new tokens): 'cancel_transfer'

21:46:47 llm: LLM call: 591 prompt tokens, decoding={'do_sample': False}

21:46:48 llm: LLM output (4 new tokens): 'top_up_failed'

21:46:48 llm: LLM call: 594 prompt tokens, decoding={'do_sample': False}

21:46:49 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:46:49 llm: LLM call: 614 prompt tokens, decoding={'do_sample': False}

21:46:50 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:46:50 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:51 llm: LLM output (9 new tokens): 'intent: transfer_not_received_by_recipient'

21:46:51 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:52 llm: LLM output (4 new tokens): 'get_virtual_card'

21:46:52 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:52 llm: LLM output (4 new tokens): 'get_physical_card'

21:46:52 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:53 llm: LLM output (4 new tokens): 'get_virtual_card'

21:46:53 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:54 llm: LLM output (4 new tokens): 'get_virtual_card'

21:46:54 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:46:55 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:46:55 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:46:56 llm: LLM output (4 new tokens): 'card_acceptance'

21:46:56 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:46:57 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:46:57 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:46:57 llm: LLM output (4 new tokens): 'top_up_failed'

21:46:57 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:46:58 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:46:58 llm: LLM call: 590 prompt tokens, decoding={'do_sample': False}

21:46:59 llm: LLM output (4 new tokens): 'pending_top_up'

21:46:59 llm: LLM call: 601 prompt tokens, decoding={'do_sample': False}

21:47:00 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:47:00 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:01 llm: LLM output (3 new tokens): 'change_pin'

21:47:01 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:47:02 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:47:02 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:03 llm: LLM output (4 new tokens): 'verify_my_identity'

21:47:03 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:03 llm: LLM output (4 new tokens): 'verify_my_identity'

21:47:03 llm: LLM call: 593 prompt tokens, decoding={'do_sample': False}

21:47:04 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:47:04 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:05 llm: LLM output (3 new tokens): 'pending_transfer'

21:47:05 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:06 llm: LLM output (5 new tokens): 'disposable_card_limits'

21:47:06 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:07 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:47:07 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:08 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:47:08 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:09 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:47:09 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:47:09 llm: LLM output (5 new tokens): 'compromised_card'

21:47:09 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:10 llm: LLM output (4 new tokens): 'atm_support'

21:47:10 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:47:11 llm: LLM output (4 new tokens): 'atm_support'

21:47:11 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:47:12 llm: LLM output (4 new tokens): 'card_acceptance'

21:47:12 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:13 llm: LLM output (3 new tokens): 'pending_transfer'

21:47:13 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:13 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:47:13 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:47:14 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:47:14 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:47:15 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:47:15 llm: LLM call: 608 prompt tokens, decoding={'do_sample': False}

21:47:16 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:47:16 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:17 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:47:17 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:18 llm: LLM output (7 new tokens): 'card_payment_not_recognised'

21:47:18 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:47:19 llm: LLM output (5 new tokens): 'declined_card_payment'

21:47:19 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:47:20 llm: LLM output (3 new tokens): 'terminate_account'

21:47:20 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:20 llm: LLM output (3 new tokens): 'terminate_account'

21:47:20 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:21 llm: LLM output (4 new tokens): 'card_swallowed'

21:47:21 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:22 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:47:22 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:23 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:47:23 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:47:24 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:47:24 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:24 llm: LLM output (3 new tokens): 'transfer_timing'

21:47:24 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:47:25 llm: LLM output (3 new tokens): 'transfer_timing'

21:47:25 llm: LLM call: 608 prompt tokens, decoding={'do_sample': False}

21:47:26 llm: LLM output (4 new tokens): 'card_not_working'

21:47:26 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:27 llm: LLM output (3 new tokens): 'change_pin'

21:47:27 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:28 llm: LLM output (4 new tokens): 'top_up_limits'

21:47:28 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:47:28 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:47:28 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:47:29 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:47:29 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:30 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:47:30 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:31 llm: LLM output (4 new tokens): 'verify_my_identity'

21:47:31 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:32 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:47:32 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:33 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:47:33 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:34 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:47:34 llm: LLM call: 596 prompt tokens, decoding={'do_sample': False}

21:47:34 llm: LLM output (6 new tokens): 'top_up_options_not_available'

21:47:35 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:47:35 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:47:35 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:36 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:47:36 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:37 llm: LLM output (4 new tokens): 'get_physical_card'

21:47:37 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:47:38 llm: LLM output (4 new tokens): 'get_physical_card'

21:47:38 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:47:39 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:47:39 llm: LLM call: 592 prompt tokens, decoding={'do_sample': False}

21:47:40 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:47:40 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:47:41 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:47:41 llm: LLM call: 595 prompt tokens, decoding={'do_sample': False}

21:47:42 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:47:42 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:42 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:47:43 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:43 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:47:43 llm: LLM call: 596 prompt tokens, decoding={'do_sample': False}

21:47:44 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:47:44 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:45 llm: LLM output (4 new tokens): 'top_up_failed'

21:47:45 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:47:46 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:47:46 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:47:47 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:47:47 llm: LLM call: 606 prompt tokens, decoding={'do_sample': False}

21:47:48 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:47:48 llm: LLM call: 607 prompt tokens, decoding={'do_sample': False}

21:47:49 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:47:49 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:47:49 llm: LLM output (4 new tokens): 'activate_my_card'

21:47:49 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:47:50 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:47:50 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:47:51 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:47:51 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:52 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:47:52 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:53 llm: LLM output (4 new tokens): 'top_up_failed'

21:47:53 llm: LLM call: 591 prompt tokens, decoding={'do_sample': False}

21:47:54 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:47:54 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:47:55 llm: LLM output (4 new tokens): 'verify_my_identity'

21:47:55 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:47:55 llm: LLM output (4 new tokens): 'verify_my_identity'

21:47:55 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:47:56 llm: LLM output (4 new tokens): 'verify_my_identity'

21:47:56 llm: LLM call: 590 prompt tokens, decoding={'do_sample': False}

21:47:57 llm: LLM output (4 new tokens): 'get_physical_card'

21:47:57 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:47:57 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:47:57 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:47:57 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:47:57 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:47:57 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:47:57 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:47:57 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:47:57 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:47:57 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:47:57 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:47:57 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:47:57 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:47:57 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:47:57 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:47:57 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:47:57 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:47:57 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:47:57 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:47:57 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:47:57 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:47:57 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:47:57 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:47:57 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:47:57 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:47:57 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:47:57 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:47:57 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:47:57 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:47:57 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:47:57 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:47:57 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:47:57 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:47:57 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:47:57 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:47:57 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:47:57 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:47:57 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:47:57 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:47:57 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:47:57 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:47:57 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:47:57 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:47:57 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:47:57 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:47:57 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:47:57 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:47:57 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:47:57 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:47:57 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:47:57 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:47:57 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:47:57 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:47:57 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:47:57 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:47:57 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:47:57 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:47:57 baseline: parse_intent: found ['top_up_limits'] in output -> 'top_up_limits'

21:47:57 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:47:57 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:47:57 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:47:57 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:47:57 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:47:57 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:47:57 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found nothing in output -> ''

21:47:57 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:47:57 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:47:57 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:47:57 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:47:57 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:47:57 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:47:57 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:47:57 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:47:57 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:47:57 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:47:57 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:47:57 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:47:57 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:47:57 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:47:57 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:47:57 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:47:57 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:47:57 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:47:57 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:47:57 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:47:57 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:47:57 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:47:57 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:47:57 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

== few_shot_constraint: accuracy 0.43
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

             prompt  accuracy  no_intent  preamble
          zero_shot      0.41          4        57
               role      0.40          4        30
         constraint      0.40          2         0
           few_shot      0.43         12         1
few_shot_constraint      0.43          8         0

Results:

In [8]:
from src.prompts import STYLES, build_prompt as prompt_by_style

rows = []
for s in STYLES:
    r = pd.read_csv(f"evaluation/results/results_{s}.csv")
    rows.append({"prompt": s, "accuracy": r.correct.mean(), "no_intent": r.predicted.isna().sum(), "preamble": r.output.str.match(r"^\s*The").sum()})
display(pd.DataFrame(rows))

print("--- constraint prompt (tail) ---")
print(prompt_by_style("How do I track my card?", "constraint")[0]["content"][-250:])

                prompt  accuracy  no_intent  preamble
0            zero_shot      0.41          4        57
1                 role      0.40          4        30
2           constraint      0.40          2         0
3             few_shot      0.43         12         1
4  few_shot_constraint      0.43          8         0

--- constraint prompt (tail) ---
sa_or_mastercard, why_verify_identity, wrong_amount_of_cash_received, wrong_exchange_rate_for_cash_withdrawal
Reply with the exact intent name from the list and nothing else. Always choose exactly one intent.

Message: How do I track my card?
Intent:

## 5. E3 Decoding comparison (Req 7)

Same prompt (`few_shot_constraint`), five decoding settings: greedy, temperature 0.7, temperature 1.5, top-k 50, top-p 0.9. Sampling runs are seeded.

**Result:** no setting beats greedy in a meaningful way (0.38 to 0.44). A one-label answer has one correct token sequence; randomness can only move away from the model's best guess.
Higher temperature produced more invented labels. Greedy is used for the intent step in the final system; sampling is used only for the free-text reply.

Run the experiment (about 8 minutes on an M3 Mac, less on a GPU):

In [9]:
%run -m src.decoding

21:48:03 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:04 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:48:04 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:05 llm: LLM output (4 new tokens): 'card_arrival'

21:48:05 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:48:05 llm: LLM output (3 new tokens): 'exchange_rate'

21:48:05 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:06 llm: LLM output (3 new tokens): 'exchange_rate'

21:48:06 llm: LLM call: 595 prompt tokens, decoding={'do_sample': False}

21:48:07 llm: LLM output (3 new tokens): 'pending_transfer'

21:48:07 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:48:08 llm: LLM output (4 new tokens): 'card_arrival'

21:48:08 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:08 llm: LLM output (4 new tokens): 'card_arrival'

21:48:08 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:48:09 llm: LLM output (4 new tokens): 'card_not_working'

21:48:09 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:10 llm: LLM output (4 new tokens): 'card_not_working'

21:48:10 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:11 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:48:11 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:48:12 llm: LLM output (3 new tokens): 'exchange_currency'

21:48:12 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:48:14 llm: LLM output (32 new tokens): 'None of the provided intents match the given message "Can I open an account for a child?". The message does not fit any of the categories listed in the'

21:48:14 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:48:14 llm: LLM output (6 new tokens): 'passcode_forgotten'

21:48:14 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:48:15 llm: LLM output (3 new tokens): 'pin_blocked'

21:48:15 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:48:16 llm: LLM output (5 new tokens): 'contactless_not_working'

21:48:16 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:17 llm: LLM output (5 new tokens): 'contactless_not_working'

21:48:17 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:48:18 llm: LLM output (5 new tokens): 'top_up_reverted'

21:48:18 llm: LLM call: 603 prompt tokens, decoding={'do_sample': False}

21:48:18 llm: LLM output (3 new tokens): 'cancel_transfer'

21:48:18 llm: LLM call: 591 prompt tokens, decoding={'do_sample': False}

21:48:19 llm: LLM output (4 new tokens): 'top_up_failed'

21:48:19 llm: LLM call: 594 prompt tokens, decoding={'do_sample': False}

21:48:20 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:48:20 llm: LLM call: 614 prompt tokens, decoding={'do_sample': False}

21:48:21 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:48:21 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:22 llm: LLM output (9 new tokens): 'intent: transfer_not_received_by_recipient'

21:48:22 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:23 llm: LLM output (4 new tokens): 'get_virtual_card'

21:48:23 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:24 llm: LLM output (4 new tokens): 'get_physical_card'

21:48:24 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:24 llm: LLM output (4 new tokens): 'get_virtual_card'

21:48:24 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:25 llm: LLM output (4 new tokens): 'get_virtual_card'

21:48:25 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:48:26 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:48:26 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:48:27 llm: LLM output (4 new tokens): 'card_acceptance'

21:48:27 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:28 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:48:28 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:48:29 llm: LLM output (4 new tokens): 'top_up_failed'

21:48:29 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:48:30 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:48:30 llm: LLM call: 590 prompt tokens, decoding={'do_sample': False}

21:48:30 llm: LLM output (4 new tokens): 'pending_top_up'

21:48:30 llm: LLM call: 601 prompt tokens, decoding={'do_sample': False}

21:48:31 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:48:31 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:48:32 llm: LLM output (3 new tokens): 'change_pin'

21:48:32 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:48:33 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:48:33 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:34 llm: LLM output (4 new tokens): 'verify_my_identity'

21:48:34 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:48:35 llm: LLM output (4 new tokens): 'verify_my_identity'

21:48:35 llm: LLM call: 593 prompt tokens, decoding={'do_sample': False}

21:48:35 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:48:35 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:48:36 llm: LLM output (3 new tokens): 'pending_transfer'

21:48:36 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:48:37 llm: LLM output (5 new tokens): 'disposable_card_limits'

21:48:37 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:38 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:48:38 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:39 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:48:39 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:48:40 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:48:40 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:48:40 llm: LLM output (5 new tokens): 'compromised_card'

21:48:40 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:48:41 llm: LLM output (4 new tokens): 'atm_support'

21:48:41 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:42 llm: LLM output (4 new tokens): 'atm_support'

21:48:42 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:48:43 llm: LLM output (4 new tokens): 'card_acceptance'

21:48:43 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:48:44 llm: LLM output (3 new tokens): 'pending_transfer'

21:48:44 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:48:44 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:48:44 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:48:45 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:48:45 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:48:46 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:48:46 llm: LLM call: 608 prompt tokens, decoding={'do_sample': False}

21:48:47 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:48:47 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:48 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:48:48 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:48:49 llm: LLM output (7 new tokens): 'card_payment_not_recognised'

21:48:49 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:48:50 llm: LLM output (5 new tokens): 'declined_card_payment'

21:48:50 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:48:51 llm: LLM output (3 new tokens): 'terminate_account'

21:48:51 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:51 llm: LLM output (3 new tokens): 'terminate_account'

21:48:51 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:48:52 llm: LLM output (4 new tokens): 'card_swallowed'

21:48:52 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:48:53 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:48:53 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:48:54 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:48:54 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:48:55 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:48:55 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:48:55 llm: LLM output (3 new tokens): 'transfer_timing'

21:48:55 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:48:56 llm: LLM output (3 new tokens): 'transfer_timing'

21:48:56 llm: LLM call: 608 prompt tokens, decoding={'do_sample': False}

21:48:57 llm: LLM output (4 new tokens): 'card_not_working'

21:48:57 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:48:58 llm: LLM output (3 new tokens): 'change_pin'

21:48:58 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:48:59 llm: LLM output (4 new tokens): 'top_up_limits'

21:48:59 llm: LLM call: 581 prompt tokens, decoding={'do_sample': False}

21:48:59 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:48:59 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:49:00 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:49:00 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:49:01 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:49:01 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:49:02 llm: LLM output (4 new tokens): 'verify_my_identity'

21:49:02 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:49:03 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:49:03 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:49:04 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:49:04 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:49:05 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:49:05 llm: LLM call: 596 prompt tokens, decoding={'do_sample': False}

21:49:05 llm: LLM output (6 new tokens): 'top_up_options_not_available'

21:49:05 llm: LLM call: 589 prompt tokens, decoding={'do_sample': False}

21:49:06 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:49:06 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:49:07 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:49:07 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:49:08 llm: LLM output (4 new tokens): 'get_physical_card'

21:49:08 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:49:09 llm: LLM output (4 new tokens): 'get_physical_card'

21:49:09 llm: LLM call: 582 prompt tokens, decoding={'do_sample': False}

21:49:10 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:49:10 llm: LLM call: 592 prompt tokens, decoding={'do_sample': False}

21:49:11 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:49:11 llm: LLM call: 583 prompt tokens, decoding={'do_sample': False}

21:49:12 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:49:12 llm: LLM call: 595 prompt tokens, decoding={'do_sample': False}

21:49:13 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:49:13 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:49:14 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:49:14 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:49:14 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:49:14 llm: LLM call: 596 prompt tokens, decoding={'do_sample': False}

21:49:15 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:49:15 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:49:16 llm: LLM output (4 new tokens): 'top_up_failed'

21:49:16 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:49:17 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:49:17 llm: LLM call: 588 prompt tokens, decoding={'do_sample': False}

21:49:18 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:49:18 llm: LLM call: 606 prompt tokens, decoding={'do_sample': False}

21:49:19 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:49:19 llm: LLM call: 607 prompt tokens, decoding={'do_sample': False}

21:49:20 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:49:20 llm: LLM call: 586 prompt tokens, decoding={'do_sample': False}

21:49:21 llm: LLM output (4 new tokens): 'activate_my_card'

21:49:21 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:49:21 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:49:21 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:49:22 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:49:22 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:49:23 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:49:23 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:49:24 llm: LLM output (4 new tokens): 'top_up_failed'

21:49:24 llm: LLM call: 591 prompt tokens, decoding={'do_sample': False}

21:49:25 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:49:25 llm: LLM call: 584 prompt tokens, decoding={'do_sample': False}

21:49:26 llm: LLM output (4 new tokens): 'verify_my_identity'

21:49:26 llm: LLM call: 585 prompt tokens, decoding={'do_sample': False}

21:49:26 llm: LLM output (4 new tokens): 'verify_my_identity'

21:49:26 llm: LLM call: 587 prompt tokens, decoding={'do_sample': False}

21:49:27 llm: LLM output (4 new tokens): 'verify_my_identity'

21:49:27 llm: LLM call: 590 prompt tokens, decoding={'do_sample': False}

21:49:28 llm: LLM output (4 new tokens): 'get_physical_card'

21:49:28 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:49:28 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:49:28 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:49:28 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:49:28 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:49:28 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:49:28 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:49:28 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:49:28 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:49:28 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:49:28 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:49:28 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:49:28 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:49:28 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:49:28 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:49:28 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:49:28 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:49:28 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:49:28 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:49:28 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:49:28 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:49:28 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:49:28 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:49:28 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:49:28 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:49:28 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:49:28 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:49:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:49:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:49:28 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:49:28 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:49:28 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:49:28 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:49:28 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:49:28 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:49:28 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:49:28 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:49:28 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:49:28 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:49:28 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:49:28 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:49:28 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:49:28 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:49:28 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:49:28 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:49:28 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:49:28 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:49:28 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:49:28 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:49:28 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:49:28 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:49:28 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:49:28 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:49:28 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:49:28 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:49:28 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:49:28 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:49:28 baseline: parse_intent: found ['top_up_limits'] in output -> 'top_up_limits'

21:49:28 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:49:28 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:49:28 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:49:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:49:28 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:49:28 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:49:28 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found nothing in output -> ''

21:49:28 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:49:28 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:49:28 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:49:28 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:49:28 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:49:28 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:49:28 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:49:28 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:49:28 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:49:28 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:49:28 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:49:28 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:49:28 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:49:28 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:49:28 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:49:28 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:49:28 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:49:28 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:49:28 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:49:28 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:49:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:49:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:49:28 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:49:28 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:49:28 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

== greedy: accuracy 0.43
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

21:49:29 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:49:29 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:30 llm: LLM output (4 new tokens): 'card_arrival'

21:49:30 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:31 llm: LLM output (3 new tokens): 'exchange_rate'

21:49:31 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:31 llm: LLM output (3 new tokens): 'exchange_rate'

21:49:31 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:32 llm: LLM output (4 new tokens): 'pending_top_up'

21:49:32 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:33 llm: LLM output (4 new tokens): 'card_arrival'

21:49:33 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:34 llm: LLM output (4 new tokens): 'card_arrival'

21:49:34 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:35 llm: LLM output (4 new tokens): 'card_not_working'

21:49:35 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:35 llm: LLM output (4 new tokens): 'card_not_working'

21:49:35 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:36 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:49:36 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:37 llm: LLM output (3 new tokens): 'exchange_currency'

21:49:37 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:39 llm: LLM output (31 new tokens): 'None of the given intents match the provided message. The message seems unrelated to any of the listed intents. Please provide more context or clarify your question.'

21:49:39 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:40 llm: LLM output (3 new tokens): 'pin_blocked'

21:49:40 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:41 llm: LLM output (3 new tokens): 'pin_blocked'

21:49:41 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:41 llm: LLM output (5 new tokens): 'contactless_not_working'

21:49:41 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:42 llm: LLM output (5 new tokens): 'contactless_not_working'

21:49:42 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:43 llm: LLM output (5 new tokens): 'top_up_reverted'

21:49:43 llm: LLM call: 603 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:44 llm: LLM output (3 new tokens): 'cancel_transfer'

21:49:44 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:45 llm: LLM output (4 new tokens): 'top_up_failed'

21:49:45 llm: LLM call: 594 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:46 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:49:46 llm: LLM call: 614 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:47 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:49:47 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:48 llm: LLM output (9 new tokens): 'intent: transfer_not_received_by_recipient'

21:49:48 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:48 llm: LLM output (4 new tokens): 'get_virtual_card'

21:49:48 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:49 llm: LLM output (4 new tokens): 'get_virtual_card'

21:49:49 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:50 llm: LLM output (4 new tokens): 'get_virtual_card'

21:49:50 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:51 llm: LLM output (4 new tokens): 'get_virtual_card'

21:49:51 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:52 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:49:52 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:53 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:49:53 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:54 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:49:54 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:54 llm: LLM output (4 new tokens): 'top_up_failed'

21:49:54 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:56 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:49:56 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:56 llm: LLM output (6 new tokens): 'pending_cash_withdrawal'

21:49:56 llm: LLM call: 601 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:57 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:49:57 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:58 llm: LLM output (10 new tokens): 'No relevant intent found in the provided messages.'

21:49:58 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:49:59 llm: LLM output (4 new tokens): 'verify_my_identity'

21:49:59 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:00 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:00 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:01 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:01 llm: LLM call: 593 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:02 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:50:02 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:02 llm: LLM output (3 new tokens): 'pending_transfer'

21:50:02 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:03 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:50:03 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:04 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:50:04 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:05 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:50:05 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:06 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:50:06 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:07 llm: LLM output (5 new tokens): 'compromised_card'

21:50:07 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:08 llm: LLM output (4 new tokens): 'atm_support'

21:50:08 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:08 llm: LLM output (4 new tokens): 'atm_support'

21:50:08 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:09 llm: LLM output (4 new tokens): 'card_acceptance'

21:50:09 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:10 llm: LLM output (3 new tokens): 'pending_transfer'

21:50:10 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:11 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:50:11 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:12 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:50:12 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:13 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:50:13 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:14 llm: LLM output (6 new tokens): 'refund_not_shown_up'

21:50:14 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:15 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:50:15 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:15 llm: LLM output (6 new tokens): 'card_payment_wrong_exchange_rate'

21:50:16 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:16 llm: LLM output (5 new tokens): 'declined_card_payment'

21:50:16 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:17 llm: LLM output (3 new tokens): 'terminate_account'

21:50:17 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:18 llm: LLM output (3 new tokens): 'terminate_account'

21:50:18 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:19 llm: LLM output (4 new tokens): 'card_swallowed'

21:50:19 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:20 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:50:20 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:20 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:50:20 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:21 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:50:21 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:22 llm: LLM output (3 new tokens): 'transfer_timing'

21:50:22 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:23 llm: LLM output (3 new tokens): 'transfer_timing'

21:50:23 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:24 llm: LLM output (4 new tokens): 'card_not_working'

21:50:24 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:24 llm: LLM output (3 new tokens): 'change_pin'

21:50:24 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:25 llm: LLM output (4 new tokens): 'top_up_limits'

21:50:25 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:26 llm: LLM output (3 new tokens): 'exchange_charge'

21:50:26 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:27 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:50:27 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:28 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:28 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:29 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:29 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:29 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:29 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:30 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:50:30 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:31 llm: LLM output (3 new tokens): 'pending_transfer'

21:50:31 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:32 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:50:32 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:33 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:50:33 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:34 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:50:34 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:35 llm: LLM output (4 new tokens): 'get_physical_card'

21:50:35 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:36 llm: LLM output (4 new tokens): 'get_physical_card'

21:50:36 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:37 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:50:37 llm: LLM call: 592 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:37 llm: LLM output (3 new tokens): 'failed_transfer'

21:50:37 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:38 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:50:38 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:39 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:50:39 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:40 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:50:40 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:41 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:50:41 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:42 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:50:42 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:43 llm: LLM output (4 new tokens): 'top_up_failed'

21:50:43 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:44 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:50:44 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:45 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:50:45 llm: LLM call: 606 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:46 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:50:46 llm: LLM call: 607 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:46 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:50:46 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:47 llm: LLM output (4 new tokens): 'activate_my_card'

21:50:47 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:48 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:50:48 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:49 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:50:49 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:50 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:50:50 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:51 llm: LLM output (4 new tokens): 'top_up_failed'

21:50:51 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:52 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:50:52 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:52 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:52 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:53 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:53 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:54 llm: LLM output (4 new tokens): 'verify_my_identity'

21:50:54 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

21:50:55 llm: LLM output (4 new tokens): 'get_physical_card'

21:50:55 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:50:55 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:50:55 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:50:55 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:50:55 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:50:55 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:50:55 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:50:55 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:50:55 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:50:55 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:50:55 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:50:55 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:50:55 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:50:55 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:50:55 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:50:55 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:50:55 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:50:55 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:50:55 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:50:55 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:50:55 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:50:55 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:50:55 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:50:55 baseline: parse_intent: found ['pending_cash_withdrawal'] in output -> 'pending_cash_withdrawal'

21:50:55 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:50:55 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:50:55 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:50:55 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:50:55 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:50:55 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:50:55 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:50:55 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:50:55 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:50:55 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:50:55 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:50:55 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:50:55 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:50:55 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:50:55 baseline: parse_intent: found ['card_payment_wrong_exchange_rate', 'exchange_rate'] in output -> 'card_payment_wrong_exchange_rate'

21:50:55 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:50:55 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:50:55 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:50:55 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:50:55 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:50:55 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:50:55 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:50:55 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:50:55 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:50:55 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:50:55 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:50:55 baseline: parse_intent: found ['top_up_limits'] in output -> 'top_up_limits'

21:50:55 baseline: parse_intent: found ['exchange_charge'] in output -> 'exchange_charge'

21:50:55 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:50:55 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:50:55 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found nothing in output -> ''

21:50:55 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:50:55 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:50:55 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:50:55 baseline: parse_intent: found ['failed_transfer'] in output -> 'failed_transfer'

21:50:55 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:50:55 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:50:55 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:50:55 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:50:55 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:50:55 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:50:55 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:50:55 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:50:55 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:50:55 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:50:55 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:50:55 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:50:55 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:50:55 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:50:55 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:50:55 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:50:55 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:50:55 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

== temperature_0.7: accuracy 0.44
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

21:50:56 llm: LLM output (4 new tokens): 'Card_delivery_estimate'

21:50:56 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:50:56 llm: LLM output (4 new tokens): 'card_arrival'

21:50:57 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:50:57 llm: LLM output (3 new tokens): 'exchange_rate'

21:50:57 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:50:58 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:50:58 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:50:59 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:50:59 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:00 llm: LLM output (4 new tokens): 'card_arrival'

21:51:00 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:01 llm: LLM output (4 new tokens): 'card_arrival'

21:51:01 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:01 llm: LLM output (4 new tokens): 'card_not_working'

21:51:01 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:02 llm: LLM output (4 new tokens): 'card_not_working'

21:51:02 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:03 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:51:03 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:04 llm: LLM output (4 new tokens): 'exchange_via_app'

21:51:04 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:05 llm: LLM output (3 new tokens): 'intent unknown'

21:51:05 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:05 llm: LLM output (3 new tokens): 'pin_blocked'

21:51:05 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:06 llm: LLM output (6 new tokens): 'passcode_forgotten'

21:51:06 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:07 llm: LLM output (5 new tokens): 'contactless_not_working'

21:51:07 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:08 llm: LLM output (5 new tokens): 'contactless_not_working'

21:51:08 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:09 llm: LLM output (5 new tokens): 'top_up_reverted'

21:51:09 llm: LLM call: 603 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:10 llm: LLM output (3 new tokens): 'cancel_transfer'

21:51:10 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:11 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:51:11 llm: LLM call: 594 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:12 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:51:12 llm: LLM call: 614 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:13 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:51:13 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:14 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:51:14 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:14 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:51:14 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:15 llm: LLM output (4 new tokens): 'get_physical_card'

21:51:15 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:16 llm: LLM output (4 new tokens): 'get_virtual_card'

21:51:16 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:17 llm: LLM output (4 new tokens): 'get_physical_card'

21:51:17 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:18 llm: LLM output (6 new tokens): 'Supported_cards_and_currencies'

21:51:18 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:19 llm: LLM output (4 new tokens): 'activate_my_card'

21:51:19 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:19 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:51:19 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:20 llm: LLM output (4 new tokens): 'top_up_failed'

21:51:20 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:21 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:51:21 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:22 llm: LLM output (5 new tokens): 'intent_type 0'

21:51:22 llm: LLM call: 601 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:23 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:51:23 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:24 llm: LLM output (4 new tokens): 'edit_personal_details'

21:51:24 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:25 llm: LLM output (4 new tokens): 'verify_my_identity'

21:51:25 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:26 llm: LLM output (4 new tokens): 'verify_my_identity'

21:51:26 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:26 llm: LLM output (4 new tokens): 'verify_my_identity'

21:51:26 llm: LLM call: 593 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:27 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:51:27 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:28 llm: LLM output (4 new tokens): 'pending_top_up'

21:51:28 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:29 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:51:29 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:30 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:51:30 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:31 llm: LLM output (5 new tokens): 'getting_spare_card'

21:51:31 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:32 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:51:32 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:32 llm: LLM output (5 new tokens): 'compromised_card'

21:51:32 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:33 llm: LLM output (4 new tokens): 'ATM_support'

21:51:33 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:34 llm: LLM output (4 new tokens): 'atm_support'

21:51:34 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:35 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:51:35 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:36 llm: LLM output (4 new tokens): 'pending_top_up'

21:51:36 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:37 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:51:37 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:38 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:51:38 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:39 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:51:39 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:39 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:51:39 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:40 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:51:40 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:41 llm: LLM output (9 new tokens): 'intent: card_payment_not_recognised'

21:51:41 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:42 llm: LLM output (5 new tokens): 'declined_card_payment'

21:51:42 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:43 llm: LLM output (3 new tokens): 'terminate_account'

21:51:43 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:44 llm: LLM output (3 new tokens): 'terminate_account'

21:51:44 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:45 llm: LLM output (4 new tokens): 'card_swallowed'

21:51:45 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:45 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:51:45 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:46 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:51:46 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:47 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:51:47 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:48 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:51:48 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:49 llm: LLM output (3 new tokens): 'transfer_timing'

21:51:49 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:50 llm: LLM output (4 new tokens): 'card_not_working'

21:51:50 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:51 llm: LLM output (3 new tokens): 'change_pin'

21:51:51 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:51 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:51:51 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:52 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:51:52 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:53 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:51:53 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:54 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:51:54 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:55 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:51:55 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:56 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:51:56 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:57 llm: LLM output (5 new tokens): 'top_up_charge_limit'

21:51:57 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:58 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:51:58 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:51:59 llm: LLM output (4 new tokens): 'top_up_limits'

21:51:59 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:00 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:52:00 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:01 llm: LLM output (30 new tokens): 'top_up_by_check\n\nMessage: Is there an upper limit when purchasing a gift using the "gift certificate" feature?\nIntent: transfer_into_account'

21:52:01 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:02 llm: LLM output (4 new tokens): 'get_physical_card'

21:52:02 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:03 llm: LLM output (4 new tokens): 'get_physical_card'

21:52:03 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:04 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:52:04 llm: LLM call: 592 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:05 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:52:05 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:06 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:52:06 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:06 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:52:06 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:07 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:52:07 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:08 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:52:08 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:09 llm: LLM output (4 new tokens): 'declined_transfer'

21:52:09 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:10 llm: LLM output (10 new tokens): 'intent unknown (due to lack of context)'

21:52:10 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:11 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:52:11 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:12 llm: LLM output (3 new tokens): 'pending_transfer'

21:52:12 llm: LLM call: 606 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:13 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:52:13 llm: LLM call: 607 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:14 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:52:14 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:14 llm: LLM output (4 new tokens): 'activate_my_card'

21:52:14 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:15 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:52:15 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:16 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:52:16 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:17 llm: LLM output (4 new tokens): 'card_arrival'

21:52:17 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:18 llm: LLM output (8 new tokens): 'Intent: google_pay_failed_top_up'

21:52:18 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:19 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:52:19 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:20 llm: LLM output (4 new tokens): 'verify_my_identity'

21:52:20 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:20 llm: LLM output (4 new tokens): 'verify_my_identity'

21:52:20 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:21 llm: LLM output (4 new tokens): 'verify_my_identity'

21:52:21 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 1.5}

21:52:22 llm: LLM output (4 new tokens): 'order_physical_card'

21:52:22 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:52:22 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:52:22 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:52:22 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:52:22 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:52:22 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:52:22 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:52:22 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:52:22 baseline: parse_intent: found ['exchange_via_app'] in output -> 'exchange_via_app'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:52:22 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:52:22 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:52:22 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:52:22 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:52:22 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:52:22 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:52:22 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:52:22 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:52:22 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:52:22 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:52:22 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:52:22 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:52:22 baseline: parse_intent: found ['edit_personal_details'] in output -> 'edit_personal_details'

21:52:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:52:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:52:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:52:22 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:52:22 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:52:22 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:52:22 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:52:22 baseline: parse_intent: found ['getting_spare_card'] in output -> 'getting_spare_card'

21:52:22 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:52:22 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:52:22 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:52:22 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:52:22 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:52:22 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:52:22 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:52:22 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:52:22 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:52:22 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:52:22 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:52:22 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:52:22 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:52:22 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:52:22 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:52:22 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:52:22 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:52:22 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:52:22 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:52:22 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:52:22 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:52:22 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:52:22 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:52:22 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:52:22 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:52:22 baseline: parse_intent: found ['top_up_limits'] in output -> 'top_up_limits'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['transfer_into_account'] in output -> 'transfer_into_account'

21:52:22 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:52:22 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:52:22 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:52:22 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:52:22 baseline: parse_intent: found ['declined_transfer'] in output -> 'declined_transfer'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:52:22 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:52:22 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:52:22 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:52:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:52:22 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:52:22 baseline: parse_intent: found nothing in output -> ''

21:52:22 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:52:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:52:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:52:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:52:22 baseline: parse_intent: found ['order_physical_card'] in output -> 'order_physical_card'

21:52:22 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

== temperature_1.5: accuracy 0.40
  'How do I track my card?' -> 'Card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

21:52:23 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:52:23 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:24 llm: LLM output (4 new tokens): 'card_arrival'

21:52:24 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:25 llm: LLM output (3 new tokens): 'exchange_rate'

21:52:25 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:25 llm: LLM output (3 new tokens): 'exchange_rate'

21:52:25 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:26 llm: LLM output (4 new tokens): 'pending_top_up'

21:52:26 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:27 llm: LLM output (4 new tokens): 'get_physical_card'

21:52:27 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:28 llm: LLM output (4 new tokens): 'card_arrival'

21:52:28 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:29 llm: LLM output (4 new tokens): 'card_not_working'

21:52:29 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:29 llm: LLM output (4 new tokens): 'card_not_working'

21:52:29 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:30 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:52:30 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:31 llm: LLM output (3 new tokens): 'exchange_currency'

21:52:31 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:33 llm: LLM output (27 new tokens): 'None of the given options match the provided message accurately. Please provide a different or additional context so that I can assist you correctly.'

21:52:33 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:33 llm: LLM output (3 new tokens): 'pin_blocked'

21:52:33 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:34 llm: LLM output (3 new tokens): 'pin_blocked'

21:52:34 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:35 llm: LLM output (5 new tokens): 'contactless_not_working'

21:52:35 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:36 llm: LLM output (5 new tokens): 'contactless_not_working'

21:52:36 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:37 llm: LLM output (7 new tokens): 'Intent: top_up_reverted'

21:52:37 llm: LLM call: 603 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:38 llm: LLM output (3 new tokens): 'cancel_transfer'

21:52:38 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:38 llm: LLM output (5 new tokens): 'top_up_reverted'

21:52:38 llm: LLM call: 594 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:40 llm: LLM output (11 new tokens): 'intent: cash_withdrawal_not_recognised'

21:52:40 llm: LLM call: 614 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:41 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:52:41 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:42 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:52:42 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:42 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:52:42 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:43 llm: LLM output (4 new tokens): 'get_virtual_card'

21:52:43 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:44 llm: LLM output (4 new tokens): 'get_virtual_card'

21:52:44 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:45 llm: LLM output (4 new tokens): 'get_physical_card'

21:52:45 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:46 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:52:46 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:47 llm: LLM output (4 new tokens): 'card_acceptance'

21:52:47 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:47 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:52:47 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:48 llm: LLM output (4 new tokens): 'top_up_failed'

21:52:48 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:49 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:52:49 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:50 llm: LLM output (7 new tokens): 'balance_not_updated_after_cash_deposit'

21:52:50 llm: LLM call: 601 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:51 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:52:51 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:52 llm: LLM output (4 new tokens): 'verify_my_identity'

21:52:52 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:53 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:52:53 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:54 llm: LLM output (4 new tokens): 'verify_my_identity'

21:52:54 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:55 llm: LLM output (4 new tokens): 'verify_my_identity'

21:52:55 llm: LLM call: 593 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:55 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:52:55 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:56 llm: LLM output (4 new tokens): 'pending_top_up'

21:52:56 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:57 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:52:57 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:58 llm: LLM output (4 new tokens): 'Disposable_card_limits'

21:52:58 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:52:59 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:52:59 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:00 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:53:00 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:00 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:53:00 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:01 llm: LLM output (4 new tokens): 'atm_support'

21:53:01 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:02 llm: LLM output (4 new tokens): 'atm_support'

21:53:02 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:03 llm: LLM output (4 new tokens): 'card_acceptance'

21:53:03 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:04 llm: LLM output (3 new tokens): 'pending_transfer'

21:53:04 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:05 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:53:05 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:05 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:53:06 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:06 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:53:06 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:07 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:53:07 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:08 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:53:08 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:09 llm: LLM output (6 new tokens): 'card_payment_wrong_exchange_rate'

21:53:09 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:10 llm: LLM output (5 new tokens): 'declined_card_payment'

21:53:10 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:11 llm: LLM output (3 new tokens): 'terminate_account'

21:53:11 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:11 llm: LLM output (3 new tokens): 'terminate_account'

21:53:11 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:12 llm: LLM output (4 new tokens): 'card_swallowed'

21:53:12 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:13 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:53:13 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:14 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:53:14 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:15 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:53:15 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:16 llm: LLM output (3 new tokens): 'transfer_timing'

21:53:16 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:16 llm: LLM output (3 new tokens): 'transfer_timing'

21:53:16 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:17 llm: LLM output (4 new tokens): 'card_not_working'

21:53:17 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:18 llm: LLM output (3 new tokens): 'change_pin'

21:53:18 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:19 llm: LLM output (4 new tokens): 'top_up_limits'

21:53:19 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:20 llm: LLM output (3 new tokens): 'exchange_charge'

21:53:20 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:20 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:53:20 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:21 llm: LLM output (4 new tokens): 'verify_my_identity'

21:53:21 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:22 llm: LLM output (4 new tokens): 'verify_my_identity'

21:53:22 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:23 llm: LLM output (4 new tokens): 'verify_my_identity'

21:53:23 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:24 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:53:24 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:25 llm: LLM output (3 new tokens): 'pending_transfer'

21:53:25 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:26 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:53:26 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:27 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:53:27 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:28 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:53:28 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:28 llm: LLM output (4 new tokens): 'get_physical_card'

21:53:28 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:29 llm: LLM output (4 new tokens): 'get_physical_card'

21:53:29 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:30 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:53:30 llm: LLM call: 592 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:31 llm: LLM output (3 new tokens): 'failed_transfer'

21:53:31 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:32 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:53:32 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:33 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:53:33 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:34 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:53:34 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:34 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:53:34 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:35 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:53:35 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:36 llm: LLM output (4 new tokens): 'top_up_failed'

21:53:36 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:37 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:53:37 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:38 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:53:38 llm: LLM call: 606 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:39 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:53:39 llm: LLM call: 607 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:40 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:53:40 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:40 llm: LLM output (4 new tokens): 'activate_my_card'

21:53:40 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:41 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:53:41 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:42 llm: LLM output (6 new tokens): 'cash_withdrawal_charge'

21:53:42 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:43 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:53:43 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:44 llm: LLM output (6 new tokens): 'intent: top_up_failed'

21:53:44 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:45 llm: LLM output (4 new tokens): 'transfer_into_account'

21:53:45 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:46 llm: LLM output (4 new tokens): 'verify_my_identity'

21:53:46 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:46 llm: LLM output (4 new tokens): 'verify_my_identity'

21:53:46 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:47 llm: LLM output (4 new tokens): 'verify_my_identity'

21:53:47 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 50}

21:53:48 llm: LLM output (4 new tokens): 'get_physical_card'

21:53:48 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:53:48 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:53:48 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:53:48 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:53:48 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:53:48 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:53:48 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:53:48 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:53:48 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:53:48 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:53:48 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:53:48 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:53:48 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:53:48 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:53:48 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:53:48 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:53:48 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:53:48 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:53:48 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:53:48 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:53:48 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:53:48 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:53:48 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:53:48 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:53:48 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:53:48 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:53:48 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:53:48 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:53:48 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:53:48 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:53:48 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:53:48 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:53:48 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:53:48 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:53:48 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:53:48 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:53:48 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:53:48 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:53:48 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:53:48 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:53:48 baseline: parse_intent: found ['card_payment_wrong_exchange_rate', 'exchange_rate'] in output -> 'card_payment_wrong_exchange_rate'

21:53:48 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:53:48 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:53:48 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:53:48 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:53:48 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:53:48 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:53:48 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:53:48 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:53:48 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:53:48 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:53:48 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:53:48 baseline: parse_intent: found ['top_up_limits'] in output -> 'top_up_limits'

21:53:48 baseline: parse_intent: found ['exchange_charge'] in output -> 'exchange_charge'

21:53:48 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:53:48 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:53:48 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found nothing in output -> ''

21:53:48 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:53:48 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:53:48 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:53:48 baseline: parse_intent: found ['failed_transfer'] in output -> 'failed_transfer'

21:53:48 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:53:48 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:53:48 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:53:48 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:53:48 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:53:48 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:53:48 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:53:48 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:53:48 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:53:48 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:53:48 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:53:48 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:53:48 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:53:48 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:53:48 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:53:48 baseline: parse_intent: found ['transfer_into_account'] in output -> 'transfer_into_account'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:53:48 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:53:48 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

== top_k_50: accuracy 0.44
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

21:53:49 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:53:49 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:50 llm: LLM output (4 new tokens): 'card_arrival'

21:53:50 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:50 llm: LLM output (3 new tokens): 'exchange_rate'

21:53:50 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:51 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:53:51 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:52 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:53:52 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:53 llm: LLM output (4 new tokens): 'card_arrival'

21:53:53 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:54 llm: LLM output (4 new tokens): 'card_arrival'

21:53:54 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:55 llm: LLM output (4 new tokens): 'card_not_working'

21:53:55 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:55 llm: LLM output (4 new tokens): 'card_not_working'

21:53:55 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:56 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:53:56 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:57 llm: LLM output (3 new tokens): 'exchange_currency'

21:53:57 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:58 llm: LLM output (4 new tokens): 'no action_required'

21:53:58 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:53:59 llm: LLM output (3 new tokens): 'pin_blocked'

21:53:59 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:00 llm: LLM output (6 new tokens): 'passcode_forgotten'

21:54:00 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:02 llm: LLM output (5 new tokens): 'contactless_not_working'

21:54:02 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:03 llm: LLM output (5 new tokens): 'contactless_not_working'

21:54:03 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:04 llm: LLM output (5 new tokens): 'top_up_reverted'

21:54:04 llm: LLM call: 603 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:05 llm: LLM output (3 new tokens): 'cancel_transfer'

21:54:05 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:06 llm: LLM output (4 new tokens): 'top_up_failed'

21:54:06 llm: LLM call: 594 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:07 llm: LLM output (9 new tokens): 'cash_withdrawal_not_recognised'

21:54:07 llm: LLM call: 614 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:08 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:54:08 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:09 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:54:09 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:10 llm: LLM output (4 new tokens): 'get_virtual_card'

21:54:10 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:11 llm: LLM output (4 new tokens): 'get_physical_card'

21:54:11 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:12 llm: LLM output (4 new tokens): 'get_physical_card'

21:54:12 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:13 llm: LLM output (4 new tokens): 'get_physical_card'

21:54:13 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:13 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:54:13 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:14 llm: LLM output (4 new tokens): 'card_acceptance'

21:54:14 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:15 llm: LLM output (6 new tokens): 'reverted_card_payment?'

21:54:15 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:16 llm: LLM output (4 new tokens): 'top_up_failed'

21:54:16 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:17 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:54:17 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:18 llm: LLM output (4 new tokens): 'pending_top_up'

21:54:18 llm: LLM call: 601 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:19 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:54:19 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:20 llm: LLM output (5 new tokens): 'contactless_not_working'

21:54:20 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:20 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:54:20 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:21 llm: LLM output (4 new tokens): 'verify_my_identity'

21:54:21 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:22 llm: LLM output (4 new tokens): 'verify_my_identity'

21:54:22 llm: LLM call: 593 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:23 llm: LLM output (6 new tokens): 'top_up_by_card_charge'

21:54:23 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:24 llm: LLM output (3 new tokens): 'pending_transfer'

21:54:24 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:25 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:54:25 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:25 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:54:25 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:26 llm: LLM output (6 new tokens): 'limited_fiatsupport'

21:54:26 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:27 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:54:27 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:28 llm: LLM output (5 new tokens): 'compromised_card'

21:54:28 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:29 llm: LLM output (2 new tokens): 'None'

21:54:29 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:30 llm: LLM output (4 new tokens): 'atm_support'

21:54:30 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:30 llm: LLM output (4 new tokens): 'card_acceptance'

21:54:30 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:31 llm: LLM output (3 new tokens): 'pending_transfer'

21:54:31 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:32 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:54:32 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:33 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:54:33 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:34 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:54:34 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:35 llm: LLM output (6 new tokens): 'refund_not_showing_up'

21:54:35 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:36 llm: LLM output (6 new tokens): 'refund_not_showed_up'

21:54:36 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:37 llm: LLM output (7 new tokens): 'card_payment_not_recognised'

21:54:37 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:37 llm: LLM output (5 new tokens): 'declined_card_payment'

21:54:37 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:38 llm: LLM output (3 new tokens): 'terminate_account'

21:54:38 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:39 llm: LLM output (3 new tokens): 'terminate_account'

21:54:39 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:40 llm: LLM output (4 new tokens): 'Card_swallowed'

21:54:40 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:41 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:54:41 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:41 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:54:41 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:42 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:54:42 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:43 llm: LLM output (3 new tokens): 'transfer_timing'

21:54:43 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:44 llm: LLM output (3 new tokens): 'transfer_timing'

21:54:44 llm: LLM call: 608 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:45 llm: LLM output (4 new tokens): 'card_not_working'

21:54:45 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:45 llm: LLM output (3 new tokens): 'change_pin'

21:54:45 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:46 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:54:46 llm: LLM call: 581 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:47 llm: LLM output (3 new tokens): 'exchange_charge'

21:54:47 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:48 llm: LLM output (5 new tokens): 'fiat_currency_support'

21:54:48 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:49 llm: LLM output (4 new tokens): 'verify_my_identity'

21:54:49 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:50 llm: LLM output (4 new tokens): 'verify_my_identity'

21:54:50 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:50 llm: LLM output (4 new tokens): 'verify_my_identity'

21:54:50 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:51 llm: LLM output (7 new tokens): 'multiple_card_issuing_fee'

21:54:51 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:52 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:54:52 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:53 llm: LLM output (6 new tokens): 'top_up_options_not_available'

21:54:53 llm: LLM call: 589 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:54 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:54:54 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:55 llm: LLM output (9 new tokens): 'top_up_by_cheque_or_cash_deposit'

21:54:55 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:56 llm: LLM output (4 new tokens): 'get_physical_card'

21:54:56 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:57 llm: LLM output (4 new tokens): 'get_physical_card'

21:54:57 llm: LLM call: 582 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:58 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:54:58 llm: LLM call: 592 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:58 llm: LLM output (3 new tokens): 'failed_transfer'

21:54:58 llm: LLM call: 583 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:54:59 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:54:59 llm: LLM call: 595 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:00 llm: LLM output (5 new tokens): 'unable_to_verify_identity'

21:55:00 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:01 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:55:01 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:02 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:55:02 llm: LLM call: 596 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:03 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:55:03 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:04 llm: LLM output (15 new tokens): 'intent_name_not_set  (If none of the provided intents apply)'

21:55:04 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:05 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:55:05 llm: LLM call: 588 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:06 llm: LLM output (3 new tokens): 'pending_transfer'

21:55:06 llm: LLM call: 606 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:07 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:55:07 llm: LLM call: 607 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:08 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:55:08 llm: LLM call: 586 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:08 llm: LLM output (4 new tokens): 'activate_my_card'

21:55:08 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:09 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:55:09 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:10 llm: LLM output (6 new tokens): 'cash_withdrawal_charge'

21:55:10 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:11 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:55:11 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:12 llm: LLM output (6 new tokens): 'intent: top_up_failed'

21:55:12 llm: LLM call: 591 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:13 llm: LLM output (4 new tokens): 'top_up_failed'

21:55:13 llm: LLM call: 584 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:14 llm: LLM output (4 new tokens): 'verify_my_identity'

21:55:14 llm: LLM call: 585 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:14 llm: LLM output (4 new tokens): 'verify_my_identity'

21:55:14 llm: LLM call: 587 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:15 llm: LLM output (4 new tokens): 'verify_my_identity'

21:55:15 llm: LLM call: 590 prompt tokens, decoding={'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}

21:55:16 llm: LLM output (4 new tokens): 'get_physical_card'

21:55:16 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:55:16 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:55:16 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:55:16 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:55:16 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:55:16 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:55:16 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:55:16 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:55:16 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:55:16 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:55:16 baseline: parse_intent: found ['passcode_forgotten'] in output -> 'passcode_forgotten'

21:55:16 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:55:16 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:55:16 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:55:16 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:55:16 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:55:16 baseline: parse_intent: found ['cash_withdrawal_not_recognised'] in output -> 'cash_withdrawal_not_recognised'

21:55:16 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:55:16 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:55:16 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:55:16 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:55:16 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:55:16 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:55:16 baseline: parse_intent: found ['reverted_card_payment?'] in output -> 'reverted_card_payment?'

21:55:16 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:55:16 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:55:16 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:55:16 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:55:16 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:55:16 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['top_up_by_card_charge'] in output -> 'top_up_by_card_charge'

21:55:16 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:55:16 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:55:16 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:55:16 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:55:16 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:55:16 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:55:16 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:55:16 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:55:16 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:55:16 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['card_payment_not_recognised'] in output -> 'card_payment_not_recognised'

21:55:16 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:55:16 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:55:16 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:55:16 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:55:16 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:55:16 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:55:16 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:55:16 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:55:16 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:55:16 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:55:16 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:55:16 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:55:16 baseline: parse_intent: found ['exchange_charge'] in output -> 'exchange_charge'

21:55:16 baseline: parse_intent: found ['fiat_currency_support'] in output -> 'fiat_currency_support'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:55:16 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:55:16 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:55:16 baseline: parse_intent: found ['failed_transfer'] in output -> 'failed_transfer'

21:55:16 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:55:16 baseline: parse_intent: found ['unable_to_verify_identity'] in output -> 'unable_to_verify_identity'

21:55:16 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:55:16 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:55:16 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:55:16 baseline: parse_intent: found nothing in output -> ''

21:55:16 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:55:16 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:55:16 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:55:16 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:55:16 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:55:16 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:55:16 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:55:16 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:55:16 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:55:16 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:55:16 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

== top_p_0.9: accuracy 0.38
  'How do I track my card?' -> 'card_delivery_estimate' (expected card_arrival)
  'How long should my new card take to arrive?' -> 'card_arrival' (expected card_arrival)
  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

       decoding  accuracy  no_intent  mean_output_chars
         greedy      0.43          8               21.9
temperature_0.7      0.44         10               22.0
temperature_1.5      0.40          7               22.5
       top_k_50      0.44          7               22.0
      top_p_0.9      0.38         11               21.1

Results:

In [10]:
from src.decoding import SETTINGS

g = pd.read_csv("evaluation/results/results_decoding_greedy.csv")
rows = []
for name in SETTINGS:
    r = pd.read_csv(f"evaluation/results/results_decoding_{name}.csv")
    rows.append({"decoding": name, "params": SETTINGS[name], "accuracy": r.correct.mean(), "no_intent": r.predicted.isna().sum(), "rows flipped vs greedy": (r.correct != g.correct).sum()})
pd.DataFrame(rows)

,decoding,params,accuracy,no_intent,rows flipped vs greedy
0,greedy,{'do_sample': False},0.43,8,0
1,temperature_0.7,"{'do_sample': True, 'temperature': 0.7}",0.44,10,5
2,temperature_1.5,"{'do_sample': True, 'temperature': 1.5}",0.40,7,13
3,top_k_50,"{'do_sample': True, 'temperature': 1.0, 'top_k': 50}",0.44,7,7
4,top_p_0.9,"{'do_sample': True, 'temperature': 1.0, 'top_k': 0, 'top_p': 0.9}",0.38,11,11

## 6. E4 Structured output (Req 9)

The model is asked for a JSON object `{"intent": ..., "confidence": ...}`. Every output is validated with `jsonschema` against a schema
whose `intent` field is an `enum` of the 77 names. The enum turns "is this a real intent?" into a hard check.

**Result:** 100/100 valid JSON, 86/100 pass the schema. All 14 rejections were invented intent names.
The `confidence` field was not informative: the model copied the example value (0.9) and gave the same mean confidence for right and wrong answers.

Run the experiment (about 3 minutes on an M3 Mac, less on a GPU):

In [11]:
%run -m src.structured

21:55:17 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:19 llm: LLM output (21 new tokens): '{\n  "intent": "card_delivery_estimate",\n  "confidence": 0.9\n}'

21:55:19 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:55:21 llm: LLM output (21 new tokens): '{\n  "intent": "card_arrival",\n  "confidence": 0.9\n}'

21:55:21 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:55:22 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "exchange_rate",\n  "confidence": 0.9\n}\n```'

21:55:22 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:24 llm: LLM output (20 new tokens): '{\n  "intent": "exchange_rate",\n  "confidence": 0.9\n}'

21:55:24 llm: LLM call: 663 prompt tokens, decoding={'do_sample': False}

21:55:25 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "pending_transfer",\n  "confidence": 0.9\n}\n```'

21:55:25 llm: LLM call: 649 prompt tokens, decoding={'do_sample': False}

21:55:27 llm: LLM output (22 new tokens): '{\n  "intent": "get_physical_card",\n  "confidence": 0.95\n}'

21:55:27 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:55:28 llm: LLM output (21 new tokens): '{\n  "intent": "card_arrival",\n  "confidence": 0.9\n}'

21:55:28 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:55:30 llm: LLM output (22 new tokens): '{\n  "intent": "card_not_working",\n  "confidence": 0.95\n}'

21:55:30 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:32 llm: LLM output (22 new tokens): '{\n  "intent": "card_not_working",\n  "confidence": 0.95\n}'

21:55:32 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:33 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "supported_cards_and_currencies",\n  "confidence": 0.9\n}\n```'

21:55:33 llm: LLM call: 649 prompt tokens, decoding={'do_sample': False}

21:55:35 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "exchange_currency",\n  "confidence": 0.9\n}\n```'

21:55:35 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:55:36 llm: LLM output (21 new tokens): '{\n  "intent": "get_physical_card",\n  "confidence": 0.9\n}'

21:55:36 llm: LLM call: 656 prompt tokens, decoding={'do_sample': False}

21:55:38 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "pin_blocked",\n  "confidence": 0.9\n}\n```'

21:55:38 llm: LLM call: 656 prompt tokens, decoding={'do_sample': False}

21:55:40 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "pin_blocked",\n  "confidence": 0.9\n}\n```'

21:55:40 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:55:41 llm: LLM output (22 new tokens): '{\n  "intent": "contactless_not_working",\n  "confidence": 0.9\n}'

21:55:41 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:43 llm: LLM output (22 new tokens): '{\n  "intent": "contactless_not_working",\n  "confidence": 0.9\n}'

21:55:43 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:55:44 llm: LLM output (22 new tokens): '{\n  "intent": "top_up_reverted",\n  "confidence": 0.9\n}'

21:55:44 llm: LLM call: 671 prompt tokens, decoding={'do_sample': False}

21:55:46 llm: LLM output (25 new tokens): '```json\n{\n  "intent": "cancel_transfer",\n  "confidence": 0.95\n}\n```'

21:55:46 llm: LLM call: 659 prompt tokens, decoding={'do_sample': False}

21:55:48 llm: LLM output (21 new tokens): '{\n  "intent": "top_up_failed",\n  "confidence": 0.9\n}'

21:55:48 llm: LLM call: 662 prompt tokens, decoding={'do_sample': False}

21:55:50 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "wrong_amount_of_cash_received",\n  "confidence": 0.9\n}\n```'

21:55:50 llm: LLM call: 682 prompt tokens, decoding={'do_sample': False}

21:55:51 llm: LLM output (24 new tokens): '{\n  "intent": "transfer_not_received_by_recipient",\n  "confidence": 0.9\n}'

21:55:51 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:53 llm: LLM output (24 new tokens): '{\n  "intent": "transfer_not_received_by_recipient",\n  "confidence": 0.9\n}'

21:55:53 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:54 llm: LLM output (22 new tokens): '{\n  "intent": "get_virtual_card",\n  "confidence": 0.95\n}'

21:55:54 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:56 llm: LLM output (21 new tokens): '{\n  "intent": "get_virtual_card",\n  "confidence": 0.9\n}'

21:55:56 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:58 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "get_virtual_card",\n  "confidence": 0.95\n}\n```'

21:55:58 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:55:59 llm: LLM output (21 new tokens): '{\n  "intent": "get_virtual_card",\n  "confidence": 0.9\n}'

21:55:59 llm: LLM call: 649 prompt tokens, decoding={'do_sample': False}

21:56:01 llm: LLM output (23 new tokens): '{\n  "intent": "supported_cards_and_currencies",\n  "confidence": 0.9\n}'

21:56:01 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:56:03 llm: LLM output (22 new tokens): '{\n  "intent": "visa_or_mastercard",\n  "confidence": 0.9\n}'

21:56:03 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:56:04 llm: LLM output (22 new tokens): '{\n  "intent": "reverted_card_payment?",\n  "confidence": 0.9\n}'

21:56:04 llm: LLM call: 657 prompt tokens, decoding={'do_sample': False}

21:56:06 llm: LLM output (21 new tokens): '{\n  "intent": "top_up_failed",\n  "confidence": 0.9\n}'

21:56:06 llm: LLM call: 657 prompt tokens, decoding={'do_sample': False}

21:56:07 llm: LLM output (28 new tokens): '{\n  "intent": "balance_not_updated_after_cheque_or_cash_deposit",\n  "confidence": 0.95\n}'

21:56:07 llm: LLM call: 658 prompt tokens, decoding={'do_sample': False}

21:56:09 llm: LLM output (23 new tokens): '{\n  "intent": "pending_cash_withdrawal",\n  "confidence": 0.9\n}'

21:56:09 llm: LLM call: 669 prompt tokens, decoding={'do_sample': False}

21:56:11 llm: LLM output (26 new tokens): '{\n  "intent": "cash_withdrawal_not_recognised",\n  "confidence": 0.9\n}'

21:56:11 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:56:12 llm: LLM output (21 new tokens): '{\n  "intent": "edit_personal_details",\n  "confidence": 0.9\n}'

21:56:12 llm: LLM call: 656 prompt tokens, decoding={'do_sample': False}

21:56:14 llm: LLM output (25 new tokens): '```json\n{\n  "intent": "verify_my_identity",\n  "confidence": 0.9\n}\n```'

21:56:14 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:56:16 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "unable_to_verify_identity",\n  "confidence": 0.9\n}\n```'

21:56:16 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:56:17 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "unable_to_verify_identity",\n  "confidence": 0.9\n}\n```'

21:56:17 llm: LLM call: 661 prompt tokens, decoding={'do_sample': False}

21:56:19 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "top_up_by_card",\n  "confidence": 0.9\n}\n```'

21:56:19 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:56:21 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "disposable_card_limits",\n  "confidence": 0.9\n}\n```'

21:56:21 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:56:22 llm: LLM output (22 new tokens): '{\n  "intent": "disposable_card_limits",\n  "confidence": 0.9\n}'

21:56:22 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:56:24 llm: LLM output (22 new tokens): '{\n  "intent": "disposable_card_limits",\n  "confidence": 0.9\n}'

21:56:24 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:56:25 llm: LLM output (22 new tokens): '{\n  "intent": "disposable_card_limits",\n  "confidence": 0.9\n}'

21:56:25 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:56:27 llm: LLM output (23 new tokens): '{\n  "intent": "lost_or_stolen_card",\n  "confidence": 0.9\n}'

21:56:27 llm: LLM call: 656 prompt tokens, decoding={'do_sample': False}

21:56:29 llm: LLM output (23 new tokens): '{\n  "intent": "lost_or_stolen_card",\n  "confidence": 0.9\n}'

21:56:29 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:56:30 llm: LLM output (21 new tokens): '{\n  "intent": "atm_support",\n  "confidence": 0.9\n}'

21:56:30 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:56:32 llm: LLM output (21 new tokens): '{\n  "intent": "atm_support",\n  "confidence": 0.9\n}'

21:56:32 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:56:33 llm: LLM output (21 new tokens): '{\n  "intent": "card_acceptance",\n  "confidence": 0.9\n}'

21:56:33 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:56:35 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "pending_transfer",\n  "confidence": 0.9\n}\n```'

21:56:35 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:56:36 llm: LLM output (23 new tokens): '{\n  "intent": "lost_or_stolen_phone",\n  "confidence": 0.9\n}'

21:56:36 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:56:38 llm: LLM output (28 new tokens): '```json\n{\n  "intent": "transfer_not_received_by_recipient",\n  "confidence": 0.9\n}\n```'

21:56:38 llm: LLM call: 649 prompt tokens, decoding={'do_sample': False}

21:56:40 llm: LLM output (23 new tokens): '{\n  "intent": "refund_not_showing_up",\n  "confidence": 0.9\n}'

21:56:40 llm: LLM call: 676 prompt tokens, decoding={'do_sample': False}

21:56:41 llm: LLM output (28 new tokens): '```json\n{\n  "intent": "refund_not_showing_up",\n  "confidence": 0.95\n}\n```'

21:56:41 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:56:43 llm: LLM output (23 new tokens): '{\n  "intent": "refund_not_showing_up",\n  "confidence": 0.9\n}'

21:56:43 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:56:45 llm: LLM output (24 new tokens): '{\n  "intent": "card_payment_not_recognised",\n  "confidence": 0.9\n}'

21:56:45 llm: LLM call: 649 prompt tokens, decoding={'do_sample': False}

21:56:46 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "declined_card_payment",\n  "confidence": 0.9\n}\n```'

21:56:47 llm: LLM call: 657 prompt tokens, decoding={'do_sample': False}

21:56:48 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "terminate_account",\n  "confidence": 0.9\n}\n```'

21:56:48 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:56:50 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "terminate_account",\n  "confidence": 0.9\n}\n```'

21:56:50 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:56:51 llm: LLM output (21 new tokens): '{\n  "intent": "card_swallowed",\n  "confidence": 0.9\n}'

21:56:51 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:56:53 llm: LLM output (18 new tokens): '{"intent": "unable_to_verify_identity", "confidence": 0.9}'

21:56:53 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:56:54 llm: LLM output (23 new tokens): '{\n  "intent": "transaction_charged_twice",\n  "confidence": 0.9\n}'

21:56:54 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:56:56 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "verify_source_of_funds",\n  "confidence": 0.9\n}\n```'

21:56:56 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:56:58 llm: LLM output (20 new tokens): '{\n  "intent": "transfer_timing",\n  "confidence": 0.9\n}'

21:56:58 llm: LLM call: 657 prompt tokens, decoding={'do_sample': False}

21:56:59 llm: LLM output (20 new tokens): '{\n  "intent": "transfer_timing",\n  "confidence": 0.9\n}'

21:56:59 llm: LLM call: 676 prompt tokens, decoding={'do_sample': False}

21:57:01 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "card_not_working",\n  "confidence": 0.95\n}\n```'

21:57:01 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:57:03 llm: LLM output (25 new tokens): '```json\n{\n  "intent": "change_pin",\n  "confidence": 0.95\n}\n```'

21:57:03 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:57:04 llm: LLM output (21 new tokens): '{\n  "intent": "top_up_limits",\n  "confidence": 0.9\n}'

21:57:04 llm: LLM call: 649 prompt tokens, decoding={'do_sample': False}

21:57:06 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "extra_charge_on_statement",\n  "confidence": 0.9\n}\n```'

21:57:06 llm: LLM call: 657 prompt tokens, decoding={'do_sample': False}

21:57:08 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "fiat_currency_support",\n  "confidence": 0.9\n}\n```'

21:57:08 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:57:09 llm: LLM output (28 new tokens): '```json\n{\n  "intent": "verify_source_of_funds",\n  "confidence": 0.95\n}\n```'

21:57:09 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:57:11 llm: LLM output (28 new tokens): '```json\n{\n  "intent": "verify_source_of_funds",\n  "confidence": 0.95\n}\n```'

21:57:11 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:57:13 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "verify_source_of_funds",\n  "confidence": 0.9\n}\n```'

21:57:13 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:57:14 llm: LLM output (22 new tokens): '{\n  "intent": "top_up_by_card",\n  "confidence": 0.9\n}'

21:57:14 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:57:16 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "extra_charge_on_statement",\n  "confidence": 0.9\n}\n```'

21:57:16 llm: LLM call: 664 prompt tokens, decoding={'do_sample': False}

21:57:18 llm: LLM output (22 new tokens): '{\n  "intent": "top_up_by_card",\n  "confidence": 0.9\n}'

21:57:18 llm: LLM call: 657 prompt tokens, decoding={'do_sample': False}

21:57:19 llm: LLM output (23 new tokens): '{\n  "intent": "top_up_by_cheque",\n  "confidence": 0.9\n}'

21:57:19 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:57:21 llm: LLM output (23 new tokens): '{\n  "intent": "top_up_by_cheque",\n  "confidence": 0.9\n}'

21:57:21 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:57:23 llm: LLM output (21 new tokens): '{\n  "intent": "get_physical_card",\n  "confidence": 0.9\n}'

21:57:23 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:57:24 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "get_physical_card",\n  "confidence": 0.95\n}\n```'

21:57:24 llm: LLM call: 650 prompt tokens, decoding={'do_sample': False}

21:57:26 llm: LLM output (22 new tokens): '{\n  "intent": "virtual_card_not_working",\n  "confidence": 0.9\n}'

21:57:26 llm: LLM call: 660 prompt tokens, decoding={'do_sample': False}

21:57:27 llm: LLM output (22 new tokens): '{\n  "intent": "virtual_card_not_working",\n  "confidence": 0.9\n}'

21:57:27 llm: LLM call: 651 prompt tokens, decoding={'do_sample': False}

21:57:29 llm: LLM output (22 new tokens): '{\n  "intent": "virtual_card_not_working",\n  "confidence": 0.9\n}'

21:57:29 llm: LLM call: 663 prompt tokens, decoding={'do_sample': False}

21:57:31 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "cash_withdrawal_charge",\n  "confidence": 0.9\n}\n```'

21:57:31 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:57:33 llm: LLM output (30 new tokens): '```json\n{\n  "intent": "wrong_exchange_rate_for_cash_withdrawal",\n  "confidence": 0.9\n}\n```'

21:57:33 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:57:34 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "get_disposable_virtual_card",\n  "confidence": 0.9\n}\n```'

21:57:34 llm: LLM call: 664 prompt tokens, decoding={'do_sample': False}

21:57:36 llm: LLM output (22 new tokens): '{\n  "intent": "transfer_fee_charged",\n  "confidence": 0.9\n}'

21:57:36 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:57:37 llm: LLM output (21 new tokens): '{\n  "intent": "top_up_failed",\n  "confidence": 0.9\n}'

21:57:37 llm: LLM call: 656 prompt tokens, decoding={'do_sample': False}

21:57:39 llm: LLM output (25 new tokens): '{\n  "intent": "balance_not_updated_after_bank_transfer",\n  "confidence": 0.95\n}'

21:57:39 llm: LLM call: 656 prompt tokens, decoding={'do_sample': False}

21:57:41 llm: LLM output (24 new tokens): '```json\n{\n  "intent": "pending_transfer",\n  "confidence": 0.9\n}\n```'

21:57:41 llm: LLM call: 674 prompt tokens, decoding={'do_sample': False}

21:57:42 llm: LLM output (22 new tokens): '{\n  "intent": "top_up_failed",\n  "confidence": 0.95\n}'

21:57:42 llm: LLM call: 675 prompt tokens, decoding={'do_sample': False}

21:57:44 llm: LLM output (24 new tokens): '{\n  "intent": "lost_or_stolen_card",\n  "confidence": 0.95\n}'

21:57:44 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:57:45 llm: LLM output (21 new tokens): '{\n  "intent": "activate_my_card",\n  "confidence": 0.9\n}'

21:57:45 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:57:47 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "transaction_charged_twice",\n  "confidence": 0.9\n}\n```'

21:57:47 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:57:49 llm: LLM output (27 new tokens): '```json\n{\n  "intent": "cash_withdrawal_charge",\n  "confidence": 0.9\n}\n```'

21:57:49 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:57:51 llm: LLM output (22 new tokens): '{\n  "intent": "card_about_to_expire",\n  "confidence": 0.9\n}'

21:57:51 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:57:52 llm: LLM output (21 new tokens): '{\n  "intent": "top_up_failed",\n  "confidence": 0.9\n}'

21:57:52 llm: LLM call: 659 prompt tokens, decoding={'do_sample': False}

21:57:54 llm: LLM output (22 new tokens): '{\n  "intent": "top_up_by_card",\n  "confidence": 0.9\n}'

21:57:54 llm: LLM call: 652 prompt tokens, decoding={'do_sample': False}

21:57:55 llm: LLM output (25 new tokens): '```json\n{\n  "intent": "verify_my_identity",\n  "confidence": 0.9\n}\n```'

21:57:55 llm: LLM call: 653 prompt tokens, decoding={'do_sample': False}

21:57:57 llm: LLM output (25 new tokens): '```json\n{\n  "intent": "verify_my_identity",\n  "confidence": 0.9\n}\n```'

21:57:57 llm: LLM call: 655 prompt tokens, decoding={'do_sample': False}

21:57:59 llm: LLM output (26 new tokens): '```json\n{\n  "intent": "unable_to_verify_identity",\n  "confidence": 0.9\n}\n```'

21:57:59 llm: LLM call: 658 prompt tokens, decoding={'do_sample': False}

21:58:00 llm: LLM output (21 new tokens): '{\n  "intent": "get_physical_card",\n  "confidence": 0.9\n}'

valid JSON:        100/100
valid vs schema:   86/100
accuracy (all):    0.43
accuracy (valid):  0.50
mean confidence when right: 0.91
mean confidence when wrong: 0.91

validation errors:
error
schema: $.intent = 'get_virtual_card' is invalid         4
schema: $.intent = 'top_up_by_card' is invalid           4
schema: $.intent = 'refund_not_showing_up' is invalid    3
schema: $.intent = 'top_up_by_cheque' is invalid         2
schema: $.intent = 'exchange_currency' is invalid        1

examples:
  'How do I track my card?' -> '{\n  "intent": "card_delivery_estimate",\n  "confidence": 0.9\n}' (expected card_arrival)
  'How long should my new card take to arrive?' -> '{\n  "intent": "card_arrival",\n  "confidence": 0.9\n}' (expected card_arrival)
  'What foreign exchange rate will you use?' -> '```json\n{\n  "intent": "exchange_rate",\n  "confidence": 0.9\n}\n```' (expected exchange_rate)

Results:

In [12]:
import json
from src.structured import SCHEMA, parse_json

print(json.dumps({**SCHEMA, "properties": {**SCHEMA["properties"], "intent": {"type": "string", "enum": "<77 intent names>"}}}, indent=2))

r = pd.read_csv("evaluation/results/results_structured.csv")
valid = r.error.isna()
print(f"\nvalid JSON 100/100, pass schema {valid.sum()}/100, accuracy all {r.correct.mean():.2f}, accuracy valid rows {r[valid].correct.mean():.2f}")
print("confidence values:", r.confidence.value_counts().to_dict())
print("\nrejected by schema:")
display(r[~valid][["text", "category", "output", "error"]].head(5))
print("validated samples:")
r[valid][["text", "category", "output", "correct"]].head(3)

{
  "type": "object",
  "properties": {
    "intent": {
      "type": "string",
      "enum": "<77 intent names>"
    },
    "confidence": {
      "type": "number",
      "minimum": 0,
      "maximum": 1
    }
  },
  "required": [
    "intent",
    "confidence"
  ],
  "additionalProperties": false
}

valid JSON 100/100, pass schema 86/100, accuracy all 0.43, accuracy valid rows 0.50
confidence values: {0.9: 84, 0.95: 16}

rejected by schema:

,text,category,output,error
10,How do I exchange currency?,exchange_via_app,"```json\n{\n ""intent"": ""exchange_currency"",\n ""confidence"": 0.9\n}\n```",schema: $.intent = 'exchange_currency' is invalid
22,help me obtain a virtual card,getting_virtual_card,"{\n ""intent"": ""get_virtual_card"",\n ""confidence"": 0.95\n}",schema: $.intent = 'get_virtual_card' is invalid
23,Where is the virtual card located?,getting_virtual_card,"{\n ""intent"": ""get_virtual_card"",\n ""confidence"": 0.9\n}",schema: $.intent = 'get_virtual_card' is invalid
24,Can I order a virtual card?,getting_virtual_card,"```json\n{\n ""intent"": ""get_virtual_card"",\n ""confidence"": 0.95\n}\n```",schema: $.intent = 'get_virtual_card' is invalid
25,Where are the virtual cards located?,getting_virtual_card,"{\n ""intent"": ""get_virtual_card"",\n ""confidence"": 0.9\n}",schema: $.intent = 'get_virtual_card' is invalid

validated samples:

,text,category,output,correct
0,How do I track my card?,card_arrival,"{\n ""intent"": ""card_delivery_estimate"",\n ""confidence"": 0.9\n}",False
1,How long should my new card take to arrive?,card_arrival,"{\n ""intent"": ""card_arrival"",\n ""confidence"": 0.9\n}",True
2,What foreign exchange rate will you use?,exchange_rate,"```json\n{\n ""intent"": ""exchange_rate"",\n ""confidence"": 0.9\n}\n```",True

## 7. Adaptation decision: retrieval few-shot (Req 8)

Prompting (E2) and decoding (E3) left accuracy at about 0.43. The failures were near-synonym confusions, which is missing knowledge, not missing instructions.
Three options: more prompting, retrieval (RAG), or fine-tuning (PEFT). We tested retrieval: for each message, the 5 most similar
train messages (TF-IDF cosine) become the few-shot examples.

**Result: accuracy 0.84**, up from 0.43. It beats a 5-NN vote on the same examples (0.77) and the TF-IDF classifier (0.79).
Fine-tuning was not needed to pass the classical baseline. Decision: RAG.

Run the classical reference (TF-IDF + logistic regression, trained on the full train split, seconds, no LLM):

In [ ]:
%run -m evaluation.reference_classifier

Run the experiment (about 2 minutes on an M3 Mac, less on a GPU):

In [13]:
%run -m src.retrieval

21:58:01 llm: LLM call: 530 prompt tokens, decoding={'do_sample': False}

21:58:02 llm: LLM output (6 new tokens): 'intent: card_arrival'

21:58:02 llm: LLM call: 560 prompt tokens, decoding={'do_sample': False}

21:58:03 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:58:03 llm: LLM call: 534 prompt tokens, decoding={'do_sample': False}

21:58:03 llm: LLM output (3 new tokens): 'exchange_rate'

21:58:03 llm: LLM call: 527 prompt tokens, decoding={'do_sample': False}

21:58:04 llm: LLM output (3 new tokens): 'exchange_rate'

21:58:04 llm: LLM call: 545 prompt tokens, decoding={'do_sample': False}

21:58:05 llm: LLM output (3 new tokens): 'pending_transfer'

21:58:05 llm: LLM call: 516 prompt tokens, decoding={'do_sample': False}

21:58:06 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:58:06 llm: LLM call: 542 prompt tokens, decoding={'do_sample': False}

21:58:06 llm: LLM output (4 new tokens): 'card_delivery_estimate'

21:58:06 llm: LLM call: 534 prompt tokens, decoding={'do_sample': False}

21:58:07 llm: LLM output (4 new tokens): 'card_not_working'

21:58:07 llm: LLM call: 521 prompt tokens, decoding={'do_sample': False}

21:58:08 llm: LLM output (4 new tokens): 'card_not_working'

21:58:08 llm: LLM call: 528 prompt tokens, decoding={'do_sample': False}

21:58:09 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:58:09 llm: LLM call: 522 prompt tokens, decoding={'do_sample': False}

21:58:09 llm: LLM output (8 new tokens): 'intent: supported_cards_and_currencies'

21:58:09 llm: LLM call: 528 prompt tokens, decoding={'do_sample': False}

21:58:10 llm: LLM output (3 new tokens): 'age_limit'

21:58:10 llm: LLM call: 527 prompt tokens, decoding={'do_sample': False}

21:58:11 llm: LLM output (3 new tokens): 'pin_blocked'

21:58:11 llm: LLM call: 560 prompt tokens, decoding={'do_sample': False}

21:58:12 llm: LLM output (3 new tokens): 'pin_blocked'

21:58:12 llm: LLM call: 525 prompt tokens, decoding={'do_sample': False}

21:58:12 llm: LLM output (5 new tokens): 'contactless_not_working'

21:58:12 llm: LLM call: 526 prompt tokens, decoding={'do_sample': False}

21:58:13 llm: LLM output (5 new tokens): 'contactless_not_working'

21:58:13 llm: LLM call: 521 prompt tokens, decoding={'do_sample': False}

21:58:14 llm: LLM output (4 new tokens): 'pending_top_up'

21:58:14 llm: LLM call: 623 prompt tokens, decoding={'do_sample': False}

21:58:15 llm: LLM output (3 new tokens): 'cancel_transfer'

21:58:15 llm: LLM call: 580 prompt tokens, decoding={'do_sample': False}

21:58:16 llm: LLM output (6 new tokens): 'wrong_amount_of_cash_received'

21:58:16 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:58:17 llm: LLM output (7 new tokens): 'declined_cash_withdrawal'

21:58:17 llm: LLM call: 725 prompt tokens, decoding={'do_sample': False}

21:58:18 llm: LLM output (7 new tokens): 'transfer_not_received_by_recipient'

21:58:18 llm: LLM call: 531 prompt tokens, decoding={'do_sample': False}

21:58:19 llm: LLM output (9 new tokens): 'Intent: transfer_not_received_by_recipient'

21:58:19 llm: LLM call: 532 prompt tokens, decoding={'do_sample': False}

21:58:19 llm: LLM output (4 new tokens): 'getting_virtual_card'

21:58:19 llm: LLM call: 517 prompt tokens, decoding={'do_sample': False}

21:58:20 llm: LLM output (4 new tokens): 'getting_virtual_card'

21:58:20 llm: LLM call: 531 prompt tokens, decoding={'do_sample': False}

21:58:21 llm: LLM output (4 new tokens): 'getting_virtual_card'

21:58:21 llm: LLM call: 523 prompt tokens, decoding={'do_sample': False}

21:58:22 llm: LLM output (4 new tokens): 'getting_virtual_card'

21:58:22 llm: LLM call: 512 prompt tokens, decoding={'do_sample': False}

21:58:22 llm: LLM output (4 new tokens): 'card_acceptance'

21:58:22 llm: LLM call: 535 prompt tokens, decoding={'do_sample': False}

21:58:23 llm: LLM output (4 new tokens): 'card_acceptance'

21:58:23 llm: LLM call: 521 prompt tokens, decoding={'do_sample': False}

21:58:24 llm: LLM output (5 new tokens): 'top_up_reverted'

21:58:24 llm: LLM call: 520 prompt tokens, decoding={'do_sample': False}

21:58:25 llm: LLM output (4 new tokens): 'top_up_failed'

21:58:25 llm: LLM call: 570 prompt tokens, decoding={'do_sample': False}

21:58:26 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:58:26 llm: LLM call: 590 prompt tokens, decoding={'do_sample': False}

21:58:27 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:58:27 llm: LLM call: 607 prompt tokens, decoding={'do_sample': False}

21:58:28 llm: LLM output (10 new tokens): 'balance_not_updated_after_cheque_or_cash_deposit'

21:58:28 llm: LLM call: 543 prompt tokens, decoding={'do_sample': False}

21:58:29 llm: LLM output (10 new tokens): 'None of the provided intents match this message.'

21:58:29 llm: LLM call: 543 prompt tokens, decoding={'do_sample': False}

21:58:30 llm: LLM output (4 new tokens): 'why_verify_identity'

21:58:30 llm: LLM call: 528 prompt tokens, decoding={'do_sample': False}

21:58:30 llm: LLM output (6 new tokens): 'Intent: why_verify_identity'

21:58:30 llm: LLM call: 533 prompt tokens, decoding={'do_sample': False}

21:58:31 llm: LLM output (4 new tokens): 'verify_my_identity'

21:58:31 llm: LLM call: 556 prompt tokens, decoding={'do_sample': False}

21:58:32 llm: LLM output (6 new tokens): 'topping_up_by_card'

21:58:32 llm: LLM call: 545 prompt tokens, decoding={'do_sample': False}

21:58:33 llm: LLM output (4 new tokens): 'intent not specified'

21:58:33 llm: LLM call: 541 prompt tokens, decoding={'do_sample': False}

21:58:34 llm: LLM output (5 new tokens): 'disposable_card_limits'

21:58:34 llm: LLM call: 537 prompt tokens, decoding={'do_sample': False}

21:58:34 llm: LLM output (5 new tokens): 'disposable_card_limits'

21:58:34 llm: LLM call: 536 prompt tokens, decoding={'do_sample': False}

21:58:35 llm: LLM output (6 new tokens): 'intent: disposable_card_limits'

21:58:35 llm: LLM call: 537 prompt tokens, decoding={'do_sample': False}

21:58:36 llm: LLM output (5 new tokens): 'compromised_card'

21:58:36 llm: LLM call: 553 prompt tokens, decoding={'do_sample': False}

21:58:37 llm: LLM output (5 new tokens): 'compromised_card'

21:58:37 llm: LLM call: 525 prompt tokens, decoding={'do_sample': False}

21:58:38 llm: LLM output (4 new tokens): 'atm_support'

21:58:38 llm: LLM call: 535 prompt tokens, decoding={'do_sample': False}

21:58:38 llm: LLM output (4 new tokens): 'atm_support'

21:58:38 llm: LLM call: 528 prompt tokens, decoding={'do_sample': False}

21:58:39 llm: LLM output (4 new tokens): 'atm_support'

21:58:39 llm: LLM call: 526 prompt tokens, decoding={'do_sample': False}

21:58:40 llm: LLM output (4 new tokens): 'pending_card_payment'

21:58:40 llm: LLM call: 542 prompt tokens, decoding={'do_sample': False}

21:58:41 llm: LLM output (6 new tokens): 'lost_or_stolen_phone'

21:58:41 llm: LLM call: 526 prompt tokens, decoding={'do_sample': False}

21:58:41 llm: LLM output (4 new tokens): 'intent not specified'

21:58:41 llm: LLM call: 533 prompt tokens, decoding={'do_sample': False}

21:58:42 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:58:42 llm: LLM call: 613 prompt tokens, decoding={'do_sample': False}

21:58:43 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:58:43 llm: LLM call: 541 prompt tokens, decoding={'do_sample': False}

21:58:44 llm: LLM output (7 new tokens): 'Refund_not_showing_up'

21:58:44 llm: LLM call: 549 prompt tokens, decoding={'do_sample': False}

21:58:45 llm: LLM output (5 new tokens): 'declined_card_payment'

21:58:45 llm: LLM call: 517 prompt tokens, decoding={'do_sample': False}

21:58:46 llm: LLM output (5 new tokens): 'declined_card_payment'

21:58:46 llm: LLM call: 532 prompt tokens, decoding={'do_sample': False}

21:58:46 llm: LLM output (3 new tokens): 'terminate_account'

21:58:46 llm: LLM call: 529 prompt tokens, decoding={'do_sample': False}

21:58:47 llm: LLM output (3 new tokens): 'terminate_account'

21:58:47 llm: LLM call: 543 prompt tokens, decoding={'do_sample': False}

21:58:48 llm: LLM output (4 new tokens): 'card_swallowed'

21:58:48 llm: LLM call: 537 prompt tokens, decoding={'do_sample': False}

21:58:49 llm: LLM output (4 new tokens): 'card_swallowed'

21:58:49 llm: LLM call: 536 prompt tokens, decoding={'do_sample': False}

21:58:49 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:58:49 llm: LLM call: 543 prompt tokens, decoding={'do_sample': False}

21:58:50 llm: LLM output (6 new tokens): 'verify_source_of_funds'

21:58:50 llm: LLM call: 540 prompt tokens, decoding={'do_sample': False}

21:58:51 llm: LLM output (3 new tokens): 'transfer_timing'

21:58:51 llm: LLM call: 554 prompt tokens, decoding={'do_sample': False}

21:58:52 llm: LLM output (3 new tokens): 'transfer_timing'

21:58:52 llm: LLM call: 567 prompt tokens, decoding={'do_sample': False}

21:58:53 llm: LLM output (6 new tokens): 'transaction_charged_twice'

21:58:53 llm: LLM call: 539 prompt tokens, decoding={'do_sample': False}

21:58:53 llm: LLM output (3 new tokens): 'change_pin'

21:58:53 llm: LLM call: 532 prompt tokens, decoding={'do_sample': False}

21:58:54 llm: LLM output (5 new tokens): 'transfer_fee_charged'

21:58:54 llm: LLM call: 534 prompt tokens, decoding={'do_sample': False}

21:58:55 llm: LLM output (5 new tokens): 'extra_charge_on_statement'

21:58:55 llm: LLM call: 556 prompt tokens, decoding={'do_sample': False}

21:58:56 llm: LLM output (6 new tokens): 'supported_cards_and_currencies'

21:58:56 llm: LLM call: 532 prompt tokens, decoding={'do_sample': False}

21:58:57 llm: LLM output (4 new tokens): 'verify_my_identity'

21:58:57 llm: LLM call: 525 prompt tokens, decoding={'do_sample': False}

21:58:57 llm: LLM output (4 new tokens): 'verify_top_up'

21:58:57 llm: LLM call: 533 prompt tokens, decoding={'do_sample': False}

21:58:58 llm: LLM output (4 new tokens): 'verify_top_up'

21:58:58 llm: LLM call: 540 prompt tokens, decoding={'do_sample': False}

21:58:59 llm: LLM output (5 new tokens): 'getting_spare_card'

21:58:59 llm: LLM call: 525 prompt tokens, decoding={'do_sample': False}

21:59:00 llm: LLM output (5 new tokens): 'getting_spare_card'

21:59:00 llm: LLM call: 558 prompt tokens, decoding={'do_sample': False}

21:59:01 llm: LLM output (10 new tokens): 'intent: top_up_by_cash_or_cheque'

21:59:01 llm: LLM call: 565 prompt tokens, decoding={'do_sample': False}

21:59:02 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:59:02 llm: LLM call: 543 prompt tokens, decoding={'do_sample': False}

21:59:03 llm: LLM output (8 new tokens): 'top_up_by_cash_or_cheque'

21:59:03 llm: LLM call: 525 prompt tokens, decoding={'do_sample': False}

21:59:03 llm: LLM output (4 new tokens): 'get_physical_card'

21:59:03 llm: LLM call: 525 prompt tokens, decoding={'do_sample': False}

21:59:04 llm: LLM output (4 new tokens): 'order_physical_card'

21:59:04 llm: LLM call: 522 prompt tokens, decoding={'do_sample': False}

21:59:05 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:59:05 llm: LLM call: 569 prompt tokens, decoding={'do_sample': False}

21:59:06 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:59:06 llm: LLM call: 523 prompt tokens, decoding={'do_sample': False}

21:59:06 llm: LLM output (5 new tokens): 'virtual_card_not_working'

21:59:06 llm: LLM call: 606 prompt tokens, decoding={'do_sample': False}

21:59:07 llm: LLM output (11 new tokens): 'intent: wrong_exchange_rate_for_cash_withdrawal'

21:59:07 llm: LLM call: 554 prompt tokens, decoding={'do_sample': False}

21:59:08 llm: LLM output (9 new tokens): 'wrong_exchange_rate_for_cash_withdrawal'

21:59:08 llm: LLM call: 541 prompt tokens, decoding={'do_sample': False}

21:59:09 llm: LLM output (6 new tokens): 'get_disposable_virtual_card'

21:59:09 llm: LLM call: 580 prompt tokens, decoding={'do_sample': False}

21:59:10 llm: LLM output (4 new tokens): 'top_up_failed'

21:59:10 llm: LLM call: 536 prompt tokens, decoding={'do_sample': False}

21:59:11 llm: LLM output (4 new tokens): 'top_up_failed'

21:59:11 llm: LLM call: 573 prompt tokens, decoding={'do_sample': False}

21:59:12 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:59:12 llm: LLM call: 550 prompt tokens, decoding={'do_sample': False}

21:59:13 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:59:13 llm: LLM call: 654 prompt tokens, decoding={'do_sample': False}

21:59:14 llm: LLM output (7 new tokens): 'balance_not_updated_after_bank_transfer'

21:59:14 llm: LLM call: 580 prompt tokens, decoding={'do_sample': False}

21:59:15 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:59:15 llm: LLM call: 541 prompt tokens, decoding={'do_sample': False}

21:59:15 llm: LLM output (4 new tokens): 'activate_my_card'

21:59:15 llm: LLM call: 540 prompt tokens, decoding={'do_sample': False}

21:59:16 llm: LLM output (6 new tokens): 'cash_withdrawal_charge'

21:59:16 llm: LLM call: 549 prompt tokens, decoding={'do_sample': False}

21:59:17 llm: LLM output (6 new tokens): 'cash_withdrawal_charge'

21:59:17 llm: LLM call: 546 prompt tokens, decoding={'do_sample': False}

21:59:18 llm: LLM output (5 new tokens): 'card_about_to_expire'

21:59:18 llm: LLM call: 548 prompt tokens, decoding={'do_sample': False}

21:59:19 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:59:19 llm: LLM call: 571 prompt tokens, decoding={'do_sample': False}

21:59:19 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:59:19 llm: LLM call: 530 prompt tokens, decoding={'do_sample': False}

21:59:20 llm: LLM output (4 new tokens): 'verify_my_identity'

21:59:20 llm: LLM call: 531 prompt tokens, decoding={'do_sample': False}

21:59:21 llm: LLM output (4 new tokens): 'verify_my_identity'

21:59:21 llm: LLM call: 547 prompt tokens, decoding={'do_sample': False}

21:59:22 llm: LLM output (4 new tokens): 'verify_my_identity'

21:59:22 llm: LLM call: 554 prompt tokens, decoding={'do_sample': False}

21:59:22 llm: LLM output (3 new tokens): 'country_support'

21:59:22 baseline: parse_intent: found ['card_arrival'] in output -> 'card_arrival'

21:59:22 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:59:22 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:59:22 baseline: parse_intent: found ['exchange_rate'] in output -> 'exchange_rate'

21:59:22 baseline: parse_intent: found ['pending_transfer'] in output -> 'pending_transfer'

21:59:22 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:59:22 baseline: parse_intent: found ['card_delivery_estimate'] in output -> 'card_delivery_estimate'

21:59:22 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:59:22 baseline: parse_intent: found ['card_not_working'] in output -> 'card_not_working'

21:59:22 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:59:22 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:59:22 baseline: parse_intent: found ['age_limit'] in output -> 'age_limit'

21:59:22 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:59:22 baseline: parse_intent: found ['pin_blocked'] in output -> 'pin_blocked'

21:59:22 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:59:22 baseline: parse_intent: found ['contactless_not_working'] in output -> 'contactless_not_working'

21:59:22 baseline: parse_intent: found ['pending_top_up'] in output -> 'pending_top_up'

21:59:22 baseline: parse_intent: found ['cancel_transfer'] in output -> 'cancel_transfer'

21:59:22 baseline: parse_intent: found ['wrong_amount_of_cash_received'] in output -> 'wrong_amount_of_cash_received'

21:59:22 baseline: parse_intent: found ['declined_cash_withdrawal'] in output -> 'declined_cash_withdrawal'

21:59:22 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:59:22 baseline: parse_intent: found ['transfer_not_received_by_recipient'] in output -> 'transfer_not_received_by_recipient'

21:59:22 baseline: parse_intent: found ['getting_virtual_card'] in output -> 'getting_virtual_card'

21:59:22 baseline: parse_intent: found ['getting_virtual_card'] in output -> 'getting_virtual_card'

21:59:22 baseline: parse_intent: found ['getting_virtual_card'] in output -> 'getting_virtual_card'

21:59:22 baseline: parse_intent: found ['getting_virtual_card'] in output -> 'getting_virtual_card'

21:59:22 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:59:22 baseline: parse_intent: found ['card_acceptance'] in output -> 'card_acceptance'

21:59:22 baseline: parse_intent: found ['top_up_reverted'] in output -> 'top_up_reverted'

21:59:22 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:59:22 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:59:22 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:59:22 baseline: parse_intent: found ['balance_not_updated_after_cheque_or_cash_deposit'] in output -> 'balance_not_updated_after_cheque_or_cash_deposit'

21:59:22 baseline: parse_intent: found nothing in output -> ''

21:59:22 baseline: parse_intent: found ['why_verify_identity'] in output -> 'why_verify_identity'

21:59:22 baseline: parse_intent: found ['why_verify_identity'] in output -> 'why_verify_identity'

21:59:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:59:22 baseline: parse_intent: found ['topping_up_by_card'] in output -> 'topping_up_by_card'

21:59:22 baseline: parse_intent: found nothing in output -> ''

21:59:22 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:59:22 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:59:22 baseline: parse_intent: found ['disposable_card_limits'] in output -> 'disposable_card_limits'

21:59:22 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:59:22 baseline: parse_intent: found ['compromised_card'] in output -> 'compromised_card'

21:59:22 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:59:22 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:59:22 baseline: parse_intent: found ['atm_support'] in output -> 'atm_support'

21:59:22 baseline: parse_intent: found ['pending_card_payment'] in output -> 'pending_card_payment'

21:59:22 baseline: parse_intent: found ['lost_or_stolen_phone'] in output -> 'lost_or_stolen_phone'

21:59:22 baseline: parse_intent: found nothing in output -> ''

21:59:22 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:59:22 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:59:22 baseline: parse_intent: found ['Refund_not_showing_up'] in output -> 'Refund_not_showing_up'

21:59:22 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:59:22 baseline: parse_intent: found ['declined_card_payment'] in output -> 'declined_card_payment'

21:59:22 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:59:22 baseline: parse_intent: found ['terminate_account'] in output -> 'terminate_account'

21:59:22 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:59:22 baseline: parse_intent: found ['card_swallowed'] in output -> 'card_swallowed'

21:59:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:59:22 baseline: parse_intent: found ['verify_source_of_funds'] in output -> 'verify_source_of_funds'

21:59:22 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:59:22 baseline: parse_intent: found ['transfer_timing'] in output -> 'transfer_timing'

21:59:22 baseline: parse_intent: found ['transaction_charged_twice'] in output -> 'transaction_charged_twice'

21:59:22 baseline: parse_intent: found ['change_pin'] in output -> 'change_pin'

21:59:22 baseline: parse_intent: found ['transfer_fee_charged'] in output -> 'transfer_fee_charged'

21:59:22 baseline: parse_intent: found ['extra_charge_on_statement'] in output -> 'extra_charge_on_statement'

21:59:22 baseline: parse_intent: found ['supported_cards_and_currencies'] in output -> 'supported_cards_and_currencies'

21:59:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:59:22 baseline: parse_intent: found ['verify_top_up'] in output -> 'verify_top_up'

21:59:22 baseline: parse_intent: found ['verify_top_up'] in output -> 'verify_top_up'

21:59:22 baseline: parse_intent: found ['getting_spare_card'] in output -> 'getting_spare_card'

21:59:22 baseline: parse_intent: found ['getting_spare_card'] in output -> 'getting_spare_card'

21:59:22 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:59:22 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:59:22 baseline: parse_intent: found ['top_up_by_cash_or_cheque'] in output -> 'top_up_by_cash_or_cheque'

21:59:22 baseline: parse_intent: found ['get_physical_card'] in output -> 'get_physical_card'

21:59:22 baseline: parse_intent: found ['order_physical_card'] in output -> 'order_physical_card'

21:59:22 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:59:22 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:59:22 baseline: parse_intent: found ['card_not_working', 'virtual_card_not_working'] in output -> 'virtual_card_not_working'

21:59:22 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:59:22 baseline: parse_intent: found ['exchange_rate', 'wrong_exchange_rate_for_cash_withdrawal'] in output -> 'wrong_exchange_rate_for_cash_withdrawal'

21:59:22 baseline: parse_intent: found ['get_disposable_virtual_card'] in output -> 'get_disposable_virtual_card'

21:59:22 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:59:22 baseline: parse_intent: found ['top_up_failed'] in output -> 'top_up_failed'

21:59:22 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:59:22 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:59:22 baseline: parse_intent: found ['balance_not_updated_after_bank_transfer'] in output -> 'balance_not_updated_after_bank_transfer'

21:59:22 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:59:22 baseline: parse_intent: found ['activate_my_card'] in output -> 'activate_my_card'

21:59:22 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:59:22 baseline: parse_intent: found ['cash_withdrawal_charge'] in output -> 'cash_withdrawal_charge'

21:59:22 baseline: parse_intent: found ['card_about_to_expire'] in output -> 'card_about_to_expire'

21:59:22 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:59:22 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:59:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:59:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:59:22 baseline: parse_intent: found ['verify_my_identity'] in output -> 'verify_my_identity'

21:59:22 baseline: parse_intent: found ['country_support'] in output -> 'country_support'

accuracy (LLM + retrieved examples): 0.84
accuracy (5-NN vote, no LLM):        0.77
no intent found: 3
correct answer present in the 5 examples: 94/100

  'How do I track my card?' -> 'intent: card_arrival' (expected card_arrival)

  'How long should my new card take to arrive?' -> 'card_delivery_estimate' (expected card_arrival)

  'What foreign exchange rate will you use?' -> 'exchange_rate' (expected exchange_rate)

Results:

In [ ]:
from src.retrieval import retrieve, build_prompt as retrieval_prompt

r = pd.read_csv("evaluation/results/results_retrieval.csv")
print(f"LLM + retrieved examples: {r.correct.mean():.2f}    5-NN vote only: {r.knn_correct.mean():.2f}    no valid intent: {r.predicted.isna().sum()}")
print(f"LLM right where vote wrong: {(r.correct & ~r.knn_correct).sum()}, LLM wrong where vote right: {(~r.correct & r.knn_correct).sum()}")

print("\nretrieved examples for 'How do I track my card?':")
display(retrieve("How do I track my card?")[["text", "category"]])

few_shot = pd.read_csv("evaluation/results/results_few_shot.csv")
tfidf = pd.read_csv("evaluation/results/results_tfidf_logreg.csv")
pd.DataFrame({"system": ["LLM, 5 random examples (E2)", "5-NN vote, no LLM", "TF-IDF + LogReg", "LLM, 5 retrieved examples"],
              "accuracy": [round(few_shot.correct.mean(), 2), round(r.knn_correct.mean(), 2), round(tfidf.correct.mean(), 2), round(r.correct.mean(), 2)]})

## 8. E6 Evaluation and failure analysis (Req 12)

Criteria: accuracy, valid output, format discipline, reproducibility. The full table of 13 systems, 7 failure types and 11 worked cases are in `docs/FAILURES.md`.
Below: the summary across the four main systems and the rows that every system got wrong.

In [15]:
systems = {"zero_shot": "evaluation/results/results_zero_shot.csv", "few_shot_constraint": "evaluation/results/results_few_shot_constraint.csv",
           "structured": "evaluation/results/results_structured.csv", "retrieval": "evaluation/results/results_retrieval.csv"}
cmp = subset.copy()
for k, f in systems.items():
    cmp[k] = pd.read_csv(f).correct
cmp["n_right"] = cmp[list(systems)].sum(axis=1)
print({k: round(cmp[k].mean(), 2) for k in systems})
print(f"right in all 4: {(cmp.n_right == 4).sum()}, wrong in all 4: {(cmp.n_right == 0).sum()}")
retr = pd.read_csv("evaluation/results/results_retrieval.csv")
cmp.loc[cmp.n_right == 0, ["text", "category"]].assign(retrieval_output=retr.loc[cmp.n_right == 0, "output"])

{'zero_shot': np.float64(0.41), 'few_shot_constraint': np.float64(0.43), 'structured': np.float64(0.43), 'retrieval': np.float64(0.84)}
right in all 4: 24, wrong in all 4: 12

,text,category,retrieval_output
4,Why am I unable to take money from my card but the statement says the transa...,pending_cash_withdrawal,pending_transfer
9,What all currencies can be exchanged?,exchange_via_app,supported_cards_and_currencies
10,How do I exchange currency?,exchange_via_app,intent: supported_cards_and_currencies
29,On my last transaction it seem that my top-up was not successful.,top_up_reverted,top_up_failed
36,Why did I need to verfiy my identity?,why_verify_identity,verify_my_identity
49,Trouble transferring transaction contact for help,declined_transfer,intent not specified
63,"I am attempting to make a purchase online, but my card is not working. I kn...",reverted_card_payment?,transaction_charged_twice
66,What extra charges are there?,transfer_fee_charged,extra_charge_on_statement
67,Is it possible for me to get money out in a different currency?,receiving_money,supported_cards_and_currencies
68,What all is needed to verify the top-up card?,verify_top_up,verify_my_identity
76,Where can I get my card at?,order_physical_card,get_physical_card
89,There is a problem with my card. Somebody has removed money from my account ...,cash_withdrawal_not_recognised,lost_or_stolen_card

## 9. E7 Final assistant (Req 10)

`main.py` combines the conclusions: retrieval prompt, greedy decoding for the intent, schema validation with the 77-name enum,
two tools with JSON schemas (`classify_intent`, `handle_intent`), and a sampled free-text reply.

The code fixes the tool order. We tested letting the 1.5B model drive the tool loop on 8 cases and it did not succeed once:
it skipped tools, invented an intent for `handle_intent`, or claimed actions it had not taken. With a small model, control belongs in code.

`handle_intent` is a simulation, as the assignment allows.

In [16]:
from main import handle, TOOLS, INTENT_SCHEMA

print("tool schemas:", [t["function"]["name"] for t in TOOLS])
for m in ["I lost my card, please block it",
          "Why is it asking me to verify my identity",
          "My top-up for Google Pay isn't working",
          "asdf qwerty zzz"]:
    print(f"\nCustomer:  {m}")
    print(f"Assistant: {handle(m)}")

21:59:23 llm: LLM call: 527 prompt tokens, decoding={'do_sample': False}

tool schemas: ['classify_intent', 'handle_intent']

Customer:  I lost my card, please block it

21:59:24 llm: LLM output (6 new tokens): 'lost_or_stolen_card'

21:59:24 baseline: parse_intent: found ['lost_or_stolen_card'] in output -> 'lost_or_stolen_card'

21:59:24 llm: LLM call: 397 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

  [tool] classify_intent({'message': 'I lost my card, please block it'}) -> {'intent': 'lost_or_stolen_card'}
  [tool] handle_intent({'intent': 'lost_or_stolen_card'}) -> {'intent': 'lost_or_stolen_card', 'status': 'done', 'reference': 'REF-1679'}

21:59:26 llm: LLM output (39 new tokens): 'Your request to block your lost card has been processed. The reference number is REF-1679. If you have any further questions or issues, feel free to contact us again.'

21:59:26 llm: LLM call: 528 prompt tokens, decoding={'do_sample': False}

Assistant: Your request to block your lost card has been processed. The reference number is REF-1679. If you have any further questions or issues, feel free to contact us again.

Customer:  Why is it asking me to verify my identity

21:59:27 llm: LLM output (6 new tokens): 'Intent: why_verify_identity'

21:59:27 baseline: parse_intent: found ['why_verify_identity'] in output -> 'why_verify_identity'

21:59:27 llm: LLM call: 393 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

  [tool] classify_intent({'message': 'Why is it asking me to verify my identity'}) -> {'intent': 'why_verify_identity'}
  [tool] handle_intent({'intent': 'why_verify_identity'}) -> {'intent': 'why_verify_identity', 'status': 'done', 'reference': 'REF-1569'}

21:59:29 llm: LLM output (51 new tokens): "The system has identified your request as needing to verify your identity. This step helps ensure security. You can proceed through this process now if you'd like to continue using our services. Your reference number for this transaction is REF-1569."

21:59:29 llm: LLM call: 548 prompt tokens, decoding={'do_sample': False}

Assistant: The system has identified your request as needing to verify your identity. This step helps ensure security. You can proceed through this process now if you'd like to continue using our services. Your reference number for this transaction is REF-1569.

Customer:  My top-up for Google Pay isn't working

21:59:30 llm: LLM output (6 new tokens): 'apple_pay_or_google_pay'

21:59:30 baseline: parse_intent: found ['apple_pay_or_google_pay'] in output -> 'apple_pay_or_google_pay'

21:59:30 llm: LLM call: 399 prompt tokens, decoding={'do_sample': True, 'temperature': 0.7}

  [tool] classify_intent({'message': "My top-up for Google Pay isn't working"}) -> {'intent': 'apple_pay_or_google_pay'}
  [tool] handle_intent({'intent': 'apple_pay_or_google_pay'}) -> {'intent': 'apple_pay_or_google_pay', 'status': 'done', 'reference': 'REF-3862'}

21:59:32 llm: LLM output (46 new tokens): 'Your top-up for Google Pay has been successfully completed. Your reference is REF-3862. Please keep it safe for future reference. If you have any further issues, feel free to contact our customer service team.'

21:59:32 llm: LLM call: 591 prompt tokens, decoding={'do_sample': False}

Assistant: Your top-up for Google Pay has been successfully completed. Your reference is REF-3862. Please keep it safe for future reference. If you have any further issues, feel free to contact our customer service team.

Customer:  asdf qwerty zzz

21:59:33 llm: LLM output (13 new tokens): 'None of the provided messages match any of the given intents.'

21:59:33 baseline: parse_intent: found nothing in output -> ''

  [tool] classify_intent({'message': 'asdf qwerty zzz'}) -> {'error': "Could not map the message to a known intent (model said 'None of the provided messages match any of the given intents.')."}
Assistant: Sorry, I could not understand your request. Could you say it in a different way?

### Final evaluation on the held-out subset

Every table above uses `eval_subset.csv`, the development set, which also chose the final system. So 0.84 is a development score.
`heldout_subset.csv` is 100 other test rows that no experiment touched. The final classifier runs on it once.

In [ ]:
%run -m evaluation.final_eval

In [ ]:
heldout = pd.read_csv("evaluation/results/results_heldout.csv")
tfidf = pd.read_csv("evaluation/results/results_tfidf_logreg.csv")
print(f"final system, held-out: {heldout.correct.mean():.2f}    classical reference, development: {tfidf.correct.mean():.2f}")
heldout.loc[~heldout.correct, ["text", "category", "predicted"]].head(5)

### Talk to the assistant

Run this cell by hand. Type a message in the box and press Enter. Press Enter on an empty line to stop.
Note: "Run All" waits at this cell until you stop the loop.

In [ ]:
from main import handle

print("Banking assistant ready. Press Enter on an empty line to exit.")
while True:
    message = input("\nCustomer: ").strip()
    if not message:
        break
    print("Assistant:", handle(message))

## 10. Summary

| Step | Result |
|---|---|
| E1 baseline | 0.41 |
| E2 best instruction prompt | 0.43; format fixed by the constraint line |
| E3 decoding | greedy is best for a one-label answer |
| E4 structured output | 100/100 JSON, 86/100 schema-valid; enum catches invented labels |
| Reference: TF-IDF + LogReg | 0.79 on the development set; the classical bar to beat |
| Retrieval few-shot | 0.84 on the development set; the adaptation decision is RAG |
| Final system, held-out | **0.77** on 100 untouched test rows |
| Final system | retrieval + greedy + schema + code-driven tools + sampled reply |

Limits: 1.5B model on an 8 GB laptop; `handle_intent` is a stub; TF-IDF retrieval matches words, not meaning (see `docs/FAILURES.md`, type F).